export interface Game {
  slug: string
  name: string
  category: string
  emoji: string
  image?: string
  external?: string
  developer?: string
  publisher?: string
  releaseDate?: string
  genres?: string[]
  description?: string
  metaTitle?: string
  metaDescription?: string
  featuredGuides?: Guide[]
  categories?: string[]
}

export interface Guide {
  title: string
  slug: string
  category: string
  excerpt: string
  updatedAt?: string
}

export const games: Game[] = [
  // === TOP MAINSTREAM GAMES (by popularity) ===
  {
    slug: 'minecraft',
    name: 'Minecraft',
    category: 'Sandbox',
    emoji: '⛏️',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/135520/header.jpg',
    developer: 'Mojang Studios',
    publisher: 'Microsoft',
    releaseDate: '2011',
    genres: ['Sandbox', 'Survival', 'Creative', 'Multiplayer'],
    description: 'Minecraft is a sandbox game about placing blocks and going on adventures. Explore procedurally generated worlds, build structures, and survive the night.',
    metaTitle: 'Minecraft Guide, Crafting Recipes & Building Tips | Xavrito',
    metaDescription: 'Complete Minecraft guide with crafting recipes, mob farm designs, redstone circuits, and building inspiration.',
    featuredGuides: [
      { title: 'Crafting Recipes Guide', slug: 'minecraft-crafting', category: 'Crafting', excerpt: 'Every recipe in the game.' },
      { title: 'Best Mob Farms', slug: 'minecraft-mob-farms', category: 'Guides', excerpt: 'Efficient farm designs for XP and loot.' },
      { title: 'Redstone Guide', slug: 'minecraft-redstone', category: 'Guides', excerpt: 'Build incredible contraptions with redstone.' },
      { title: 'Building Ideas', slug: 'minecraft-building', category: 'Guides', excerpt: 'Design inspiration and architectural tips.' },
    ],
    categories: ['Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Achievements', 'Codes'],
  },
  {
    slug: 'gta-5',
    name: 'GTA V',
    category: 'Action',
    emoji: '🚗',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg',
    developer: 'Rockstar North',
    publisher: 'Rockstar Games',
    releaseDate: '2013',
    genres: ['Action', 'Open World', 'Multiplayer', 'Crime'],
    description: 'Grand Theft Auto V is an open-world action-adventure game. Switch between three protagonists and explore Los Santos or the endless possibilities of GTA Online.',
    metaTitle: 'GTA 5 Guide, Heist Walkthrough & Money Tips | Xavrito',
    metaDescription: 'Master GTA 5 with heist guides, money-making methods, vehicle list, and GTA Online tips.',
    featuredGuides: [
      { title: 'Heist Walkthrough', slug: 'gta-5-heist-guide', category: 'Quests', excerpt: 'Complete every heist from Prologue to The Big Score.' },
      { title: 'Money Making Guide', slug: 'gta-5-money-guide', category: 'Resources', excerpt: 'Best methods to earn money in GTA Online.' },
      { title: 'Vehicle List', slug: 'gta-5-vehicles', category: 'Guides', excerpt: 'Every car, bike, and aircraft with stats.' },
      { title: 'GTA Online Tips', slug: 'gta-5-online-tips', category: 'Beginner Guides', excerpt: 'Getting started in GTA Online.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'fortnite',
    name: 'Fortnite',
    category: 'Battle Royale',
    emoji: '🎮',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/1174180/header.jpg',
    developer: 'Epic Games',
    publisher: 'Epic Games',
    releaseDate: '2017',
    genres: ['Battle Royale', 'Shooter', 'Multiplayer', 'Creative'],
    description: 'Fortnite is a free-to-play battle royale game. Drop into the island, gather resources, build structures, and be the last one standing.',
    metaTitle: 'Fortnite Guide, Building Tips & Strategy | Xavrito',
    metaDescription: 'Master Fortnite with building tutorials, aim training guides, map rotation strategies, and late-game tactics.',
    featuredGuides: [
      { title: 'Building Mastery', slug: 'fortnite-building', category: 'Guides', excerpt: 'From beginner to advanced building techniques.' },
      { title: 'Aim Training Guide', slug: 'fortnite-aim', category: 'Beginner Guides', excerpt: 'Improve your aim with training routines.' },
      { title: 'Map Rotation Tips', slug: 'fortnite-rotation', category: 'Guides', excerpt: 'Best routes for each POI.' },
      { title: 'Late Game Strategy', slug: 'fortnite-late-game', category: 'Guides', excerpt: 'Tactics for the final circles.' },
    ],
    categories: ['Build Guides', 'Weapons', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'valorant',
    name: 'Valorant',
    category: 'FPS',
    emoji: '🎯',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/108800/header.jpg',
    developer: 'Riot Games',
    publisher: 'Riot Games',
    releaseDate: '2020',
    genres: ['FPS', 'Tactical Shooter', 'Multiplayer', 'Competitive'],
    description: 'Valorant is a free-to-play first-person tactical shooter. Choose your Agent, use unique abilities, and compete in 5v5 competitive matches.',
    metaTitle: 'Valorant Agent Guide, Lineups & Pro Tips | Xavrito',
    metaDescription: 'Master Valorant with agent guides, ability lineups, crosshair settings, and competitive strategies.',
    featuredGuides: [
      { title: 'Agent Tier List', slug: 'valorant-agent-tier', category: 'Tier Lists', excerpt: 'Best agents for the current meta.' },
      { title: 'Sova Lineups', slug: 'valorant-sova-lineups', category: 'Guides', excerpt: 'Best recon bolt and drone lineups.' },
      { title: 'Aim Training Guide', slug: 'valorant-aim', category: 'Beginner Guides', excerpt: 'Improve your aim with proven methods.' },
      { title: 'Pro Settings', slug: 'valorant-pro-settings', category: 'Guides', excerpt: 'Crosshair, sensitivity, and display settings.' },
    ],
    categories: ['Build Guides', 'Weapons', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'genshin-impact',
    name: 'Genshin Impact',
    category: 'Action RPG',
    emoji: '⭐',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/981190/header.jpg',
    developer: 'HoYoverse',
    publisher: 'HoYoverse',
    releaseDate: '2020',
    genres: ['Action RPG', 'Gacha', 'Open World', 'Fantasy'],
    description: 'Genshin Impact is a free-to-play action RPG. Explore Teyvat, collect characters, solve puzzles, and uncover the secrets of the Archons.',
    metaTitle: 'Genshin Impact Guide, Tier List & Build Guide | Xavrito',
    metaDescription: 'Master Genshin Impact with character builds, tier lists, artifact farming, and puzzle solutions.',
    featuredGuides: [
      { title: 'Character Tier List', slug: 'genshin-tier-list', category: 'Tier Lists', excerpt: 'Every character ranked by power level.' },
      { title: 'Character Builds', slug: 'genshin-character-builds', category: 'Build Guides', excerpt: 'Best weapons and artifacts for each character.' },
      { title: 'Artifact Farming Guide', slug: 'genshin-artifacts', category: 'Resources', excerpt: 'Best domains for artifact sets.' },
      { title: 'Puzzle Guide', slug: 'genshin-puzzles', category: 'Guides', excerpt: 'Solutions to all world puzzles.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'league-of-legends',
    name: 'League of Legends',
    category: 'MOBA',
    emoji: '🏆',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/2054520/header.jpg',
    developer: 'Riot Games',
    publisher: 'Riot Games',
    releaseDate: '2009',
    genres: ['MOBA', 'Strategy', 'Multiplayer', 'Competitive'],
    description: 'League of Legends is a team-based strategy game. Choose your Champion, work with your team, and destroy the enemy Nexus.',
    metaTitle: 'League of Legends Champion Guide & Tier List | Xavrito',
    metaDescription: 'Master League of Legends with champion guides, role tier lists, rune recommendations, and lane strategies.',
    featuredGuides: [
      { title: 'Champion Tier List', slug: 'lol-tier-list', category: 'Tier Lists', excerpt: 'Best champions for each role in the current patch.' },
      { title: 'Champion Builds', slug: 'lol-champion-builds', category: 'Build Guides', excerpt: 'Runes, items, and skill order for each champion.' },
      { title: 'Lane Guide', slug: 'lol-lane-guide', category: 'Guides', excerpt: 'Wave management and trading tips for each lane.' },
      { title: 'Support Guide', slug: 'lol-support-guide', category: 'Guides', excerpt: 'Roaming and vision control for supports.' },
    ],
    categories: ['Build Guides', 'Weapons', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    category: 'RPG',
    emoji: '🤖',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg',
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    releaseDate: '2020',
    genres: ['RPG', 'Open World', 'Sci-Fi', 'Action'],
    description: 'Cyberpunk 2077 is an open-world RPG set in the megalopolis of Night City. Become a cyberpunk mercenary and navigate the future.',
    metaTitle: 'Cyberpunk 2077 Guide, Builds & Mission Walkthrough | Xavrito',
    metaDescription: 'Complete Cyberpunk 2077 guide with build recommendations, side job walkthroughs, and romance guides.',
    featuredGuides: [
      { title: 'Best Builds Guide', slug: 'cyberpunk-2077-builds', category: 'Build Guides', excerpt: 'Top builds for netrunners, solos, and corpo agents.' },
      { title: 'All Side Jobs Guide', slug: 'cyberpunk-2077-side-jobs', category: 'Quests', excerpt: 'Complete every side job and gig in Night City.' },
      { title: 'Weapon Tier List', slug: 'cyberpunk-2077-weapons', category: 'Tier Lists', excerpt: 'Every weapon type ranked.' },
      { title: 'Romance Guide', slug: 'cyberpunk-2077-romance', category: 'Guides', excerpt: 'How to romance Panam, Judy, River, or Kerry.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists'],
  },
  {
    slug: 'elden-ring',
    name: 'Elden Ring',
    category: 'Action RPG',
    emoji: '⚔️',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg',
    developer: 'FromSoftware',
    publisher: 'Bandai Namco',
    releaseDate: '2022',
    genres: ['Action RPG', 'Souls-like', 'Open World', 'Fantasy'],
    description: 'Elden Ring is an action RPG developed by FromSoftware. Create your character, explore the Lands Between, and defeat powerful bosses to become the Elden Lord.',
    metaTitle: 'Elden Ring Guide, Build Tips & Boss Strategies | Xavrito',
    metaDescription: 'Complete Elden Ring guide with build recommendations, boss strategies, weapon tier lists, and location maps.',
    featuredGuides: [
      { title: 'Best Builds Guide', slug: 'elden-ring-best-builds', category: 'Build Guides', excerpt: 'Top builds for every playstyle.' },
      { title: 'Boss Fight Walkthrough', slug: 'elden-ring-boss-guide', category: 'Boss Guides', excerpt: 'Defeat every boss with attack patterns.' },
      { title: 'Weapon Tier List', slug: 'elden-ring-weapon-tier-list', category: 'Tier Lists', excerpt: 'Every weapon ranked from best to worst.' },
      { title: 'Location Map Guide', slug: 'elden-ring-map-guide', category: 'Maps', excerpt: 'Find every legendary item location.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists'],
  },
  {
    slug: 'baldurs-gate-3',
    name: "Baldur's Gate 3",
    category: 'RPG',
    emoji: '🐉',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/1086940/header.jpg',
    developer: 'Larian Studios',
    publisher: 'Larian Studios',
    releaseDate: '2023',
    genres: ['RPG', 'Turn-based', 'Fantasy', 'Co-op'],
    description: "Baldur's Gate 3 is a role-playing game based on Dungeons & Dragons. Create your character, gather your party, and explore the Forgotten Realms.",
    metaTitle: "Baldur's Gate 3 Guide, Class Builds & Walkthrough | Xavrito",
    metaDescription: "Master Baldur's Gate 3 with class builds, companion guides, puzzle solutions, and full act walkthroughs.",
    featuredGuides: [
      { title: 'Best Class Builds', slug: 'bg3-class-builds', category: 'Build Guides', excerpt: 'Optimal builds for every class.' },
      { title: 'Companion Guide', slug: 'bg3-companion-guide', category: 'Guides', excerpt: 'Complete companion quests and romance paths.' },
      { title: 'Puzzle Solutions', slug: 'bg3-puzzle-guide', category: 'Guides', excerpt: 'Solutions to all major puzzles.' },
      { title: 'Act 1 Walkthrough', slug: 'bg3-act-1-walkthrough', category: 'Quests', excerpt: 'Complete walkthrough for the first act.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'diablo-4',
    name: 'Diablo IV',
    category: 'Action RPG',
    emoji: '💀',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/2344520/header.jpg',
    developer: 'Blizzard',
    publisher: 'Blizzard',
    releaseDate: '2023',
    genres: ['Action RPG', 'Hack and Slash', 'Dark Fantasy', 'Multiplayer'],
    description: 'Diablo IV is a dark fantasy action RPG. Choose your class, explore Sanctuary, and battle against the forces of Lilith.',
    metaTitle: 'Diablo 4 Guide, Class Builds & Endgame Tips | Xavrito',
    metaDescription: 'Master Diablo 4 with class builds, item farming routes, nightmare dungeon guides, and season tips.',
    featuredGuides: [
      { title: 'Class Tier List', slug: 'd4-class-tier', category: 'Tier Lists', excerpt: 'Best classes for solo and group content.' },
      { title: 'Barbarian Builds', slug: 'd4-barbarian-builds', category: 'Build Guides', excerpt: 'Top DPS and tank builds.' },
      { title: 'Item Farming Guide', slug: 'd4-item-farming', category: 'Resources', excerpt: 'Best routes to get legendary items.' },
      { title: 'Season Journey', slug: 'd4-season-guide', category: 'Beginner Guides', excerpt: 'Complete the season journey.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'zelda-tears-kingdom',
    name: 'Zelda: TotK',
    category: 'Action Adventure',
    emoji: '🗡️',
    image: 'https://assets.nintendo.com/image/upload/c_fill,w_1200/h_630/f_auto/q_auto/ncom/software/switch/70010000000025/6d5d0a7d6a1f2c8b6e3c6f8a2b4d9e1c',
    developer: 'Nintendo',
    publisher: 'Nintendo',
    releaseDate: '2023',
    genres: ['Action Adventure', 'Open World', 'Fantasy', 'Puzzle'],
    description: 'The Legend of Zelda: Tears of the Kingdom is an open-world adventure. Use new abilities like Ultrahand and Ascend to explore Hyrule.',
    metaTitle: 'Zelda TotK Guide, Shrine Locations & Walkthrough | Xavrito',
    metaDescription: 'Complete Tears of the Kingdom guide with all shrine locations, puzzle solutions, and main story walkthrough.',
    featuredGuides: [
      { title: 'All Shrine Locations', slug: 'totk-shrine-locations', category: 'Maps', excerpt: 'Every shrine and how to solve it.' },
      { title: 'Main Quest Walkthrough', slug: 'totk-main-quest', category: 'Quests', excerpt: 'Complete main story progression.' },
      { title: 'Best Equipment', slug: 'totk-equipment', category: 'Weapons', excerpt: 'Finding the best weapons and armor.' },
      { title: 'Ability Guide', slug: 'totk-abilities', category: 'Guides', excerpt: 'Master Ultrahand, Ascend, and other powers.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Achievements'],
  },
  {
    slug: 'final-fantasy-16',
    name: 'Final Fantasy XVI',
    category: 'Action RPG',
    emoji: '🌟',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/2514900/header.jpg',
    developer: 'Square Enix',
    publisher: 'Square Enix',
    releaseDate: '2023',
    genres: ['Action RPG', 'Fantasy', 'Story-rich', 'Single Player'],
    description: 'Final Fantasy XVI is a dark fantasy action RPG. Follow Clive Rosfield as he seeks revenge and uncovers the truth about the Eikons.',
    metaTitle: 'Final Fantasy XVI Guide, Eikon Battles & Walkthrough | Xavrito',
    metaDescription: 'Complete Final Fantasy XVI guide with Eikon strategies, side quests, and complete story walkthrough.',
    featuredGuides: [
      { title: 'Eikon Boss Guide', slug: 'ff16-eikon-guide', category: 'Boss Guides', excerpt: 'Strategies for every Eikon fight.' },
      { title: 'Side Quest Guide', slug: 'ff16-side-quests', category: 'Quests', excerpt: 'All side quests and rewards.' },
      { title: 'Upgrade Guide', slug: 'ff16-upgrades', category: 'Resources', excerpt: 'Ability points and gear progression.' },
      { title: 'Best Builds', slug: 'ff16-builds', category: 'Build Guides', excerpt: 'Optimal ability loadouts.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'monster-hunter-wilds',
    name: 'Monster Hunter Wilds',
    category: 'Action RPG',
    emoji: '🐲',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/2524780/header.jpg',
    developer: 'Capcom',
    publisher: 'Capcom',
    releaseDate: '2025',
    genres: ['Action RPG', 'Hunting', 'Open World', 'Co-op'],
    description: 'Monster Hunter Wilds is the latest entry in the acclaimed action RPG series. Hunt massive monsters in diverse ecosystems and craft powerful gear.',
    metaTitle: 'Monster Hunter Wilds Guide, Weapon Builds & Monster Weaknesses | Xavrito',
    metaDescription: 'Complete Monster Hunter Wilds guide with weapon builds, monster weaknesses, and progression tips.',
    featuredGuides: [
      { title: 'Weapon Tier List', slug: 'mhw-weapon-tier', category: 'Tier Lists', excerpt: 'Every weapon type ranked.' },
      { title: 'Monster Weakness Chart', slug: 'mhw-monster-weaknesses', category: 'Resources', excerpt: 'Every monster with elemental weaknesses.' },
      { title: 'Best Builds Guide', slug: 'mhw-builds', category: 'Build Guides', excerpt: 'Optimal armor sets for each weapon.' },
      { title: 'Beginner Guide', slug: 'mhw-beginner', category: 'Beginner Guides', excerpt: 'Everything you need to start hunting.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Achievements'],
  },

  // === NICHE/GAMING COMMUNITY FAVORITES ===
  {
    slug: 'once-human',
    name: 'Once Human',
    category: 'Survival',
    emoji: '🔫',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/2125420/header.jpg',
    developer: 'Starry Interactive',
    publisher: 'Moon Studios',
    releaseDate: '2024',
    genres: ['Survival', 'Open World', 'Multiplayer', 'Zombies'],
    description: 'Once Human is a free-to-play open-world survival game set in a post-apocalyptic future. Players must gather resources, build bases, and fight against corrupted creatures.',
    metaTitle: 'Once Human Guides, Walkthroughs & Build Tips | Xavrito',
    metaDescription: 'Master Once Human with comprehensive guides on base building, combat strategies, best builds, and boss fight tactics.',
    featuredGuides: [
      { title: 'Best Builds for PvE and PvP', slug: 'once-human-best-builds', category: 'Build Guides', excerpt: 'Optimize your character with the top meta builds.' },
      { title: 'Resource Farming Guide', slug: 'once-human-resource-farming', category: 'Resources', excerpt: 'Learn efficient ways to gather resources.' },
      { title: 'Base Building Tips', slug: 'once-human-base-building', category: 'Guides', excerpt: 'Defensive layouts and storage solutions.' },
      { title: 'Boss Fight Strategies', slug: 'once-human-boss-guides', category: 'Boss Guides', excerpt: 'Defeat every boss with mechanics breakdown.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists'],
  },
  {
    slug: 'palworld',
    name: 'Palworld',
    category: 'Survival',
    emoji: '🐾',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/1623730/header.jpg',
    developer: 'Pocketpair',
    publisher: 'Pocketpair',
    releaseDate: '2024',
    genres: ['Survival', 'Open World', 'Creature Collection', 'Multiplayer'],
    description: 'Palworld is an open-world survival game featuring mysterious creature companions called Pals. Catch Pals, build bases, and survive.',
    metaTitle: 'Palworld Guide, Paldeck & Breeding Strategies | Xavrito',
    metaDescription: 'Master Palworld with complete Paldeck, breeding guides, base building tips, and best Pals tier list.',
    featuredGuides: [
      { title: 'Complete Paldeck', slug: 'palworld-paldeck', category: 'Guides', excerpt: 'Every Pal with stats and locations.' },
      { title: 'Breeding Guide', slug: 'palworld-breeding', category: 'Guides', excerpt: 'Master breeding for the best traits.' },
      { title: 'Base Building Guide', slug: 'palworld-base-building', category: 'Guides', excerpt: 'Optimal base layouts and automation.' },
      { title: 'Best Pals Tier List', slug: 'palworld-pal-tier-list', category: 'Tier Lists', excerpt: 'Ranked Pals for work and combat.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Tier Lists', 'Codes', 'Achievements'],
  },
  {
    slug: 'v-rising',
    name: 'V Rising',
    category: 'Action RPG',
    emoji: '🧛',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/1283360/header.jpg',
    developer: 'Stunlock Studios',
    publisher: 'Stunlock Studios',
    releaseDate: '2022',
    genres: ['Action RPG', 'Vampire', 'Survival', 'Multiplayer'],
    description: 'V Rising is an open-world vampire survival game where you hunt for blood to restore your powers. Build your castle and dominate.',
    metaTitle: 'V Rising Guide, Blood Types & Castle Builds | Xavrito',
    metaDescription: 'Master V Rising with guides on blood types, castle building, combat mechanics, and PvP strategies.',
    featuredGuides: [
      { title: 'Blood Types & Farming', slug: 'v-rising-blood-types', category: 'Resources', excerpt: 'Every blood type and where to find hosts.' },
      { title: 'Castle Building Guide', slug: 'v-rising-castle-builds', category: 'Guides', excerpt: 'Efficient castle layouts.' },
      { title: 'Best Spells Tier List', slug: 'v-rising-spell-tier-list', category: 'Tier Lists', excerpt: 'Ranked list of powerful spells.' },
      { title: 'PvP Combat Guide', slug: 'v-rising-pvp-guide', category: 'Guides', excerpt: 'Combat mechanics for PvP.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'core-keeper',
    name: 'Core Keeper',
    category: 'Sandbox',
    emoji: '⛏️',
    image: 'https://shared.cdn.queniuqe.com/store_item_assets/steam/apps/2244210/ad1d55b1a3acbfe421714bacd2b9ee04641120d3/capsule_616x353.jpg',
    developer: 'Farming Fantasy',
    publisher: 'Farming Fantasy',
    releaseDate: '2022',
    genres: ['Sandbox', 'Mining', 'Crafting', 'Adventure'],
    description: 'Core Keeper is a sandbox mining adventure game where players dig for resources, discover artifacts, and battle monsters.',
    metaTitle: 'Core Keeper Guide, Mining Tips & Recipes | Xavrito',
    metaDescription: 'Complete Core Keeper resource guide with mining strategies, crafting recipes, and progression tips.',
    featuredGuides: [
      { title: 'Mining Guide & Ore Progression', slug: 'core-keeper-mining-guide', category: 'Resources', excerpt: 'Master ore progression.' },
      { title: 'Crafting Recipes Complete List', slug: 'core-keeper-crafting-recipes', category: 'Crafting', excerpt: 'Every crafting recipe.' },
      { title: 'Boss Fight Guide', slug: 'core-keeper-boss-guide', category: 'Boss Guides', excerpt: 'Defeat all bosses.' },
      { title: 'Best Tools & Pickaxes', slug: 'core-keeper-best-tools', category: 'Weapons', excerpt: 'Upgrade your mining.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides'],
  },
  {
    slug: 'enshrouded',
    name: 'Enshrouded',
    category: 'Action RPG',
    emoji: '🔥',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/1913210/header.jpg',
    developer: 'Keen Software House',
    publisher: 'Keen Software House',
    releaseDate: '2023',
    genres: ['Action RPG', 'Hack and Slash', 'Souls-like', 'Open World'],
    description: 'Enshrouded is an action RPG with Souls-like combat. Explore dungeons, defeat bosses, collect equipment, and restore the world.',
    metaTitle: 'Enshrouded Guide, Boss Fight Strategies & Build Tips | Xavrito',
    metaDescription: 'Complete Enshrouded walkthrough with boss guides, best builds, weapon tier list, and alchemy recipes.',
    featuredGuides: [
      { title: 'Boss Fight Guide', slug: 'enshrouded-boss-guide', category: 'Boss Guides', excerpt: 'Strategies for every boss.' },
      { title: 'Best Builds', slug: 'enshrouded-best-builds', category: 'Build Guides', excerpt: 'Top-tier builds.' },
      { title: 'Weapon Tier List', slug: 'enshrouded-weapon-tier-list', category: 'Tier Lists', excerpt: 'Ranked weapons.' },
      { title: 'Alchemy Recipes', slug: 'enshrouded-alchemy', category: 'Crafting', excerpt: 'Every flask recipe.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Tier Lists', 'Achievements'],
  },
  {
    slug: 'soulmask',
    name: 'Soulmask',
    category: 'Survival',
    emoji: '🎭',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/2696570/header.jpg',
    developer: 'Cath Play',
    publisher: 'Koch Media',
    releaseDate: '2024',
    genres: ['Survival', 'Open World', 'Sandbox', 'Multiplayer'],
    description: 'Soulmask is a hardcore survival sandbox game featuring a unique mask system. Bind to NPCs to obtain their skills.',
    metaTitle: 'Soulmask Guide, Mask Skills & Tribe Building | Xavrito',
    metaDescription: 'Master Soulmask with guides on mask skills, tribe management, base building, and boss strategies.',
    featuredGuides: [
      { title: 'Mask Skills Guide', slug: 'soulmask-mask-skills', category: 'Guides', excerpt: 'Every mask type and skills.' },
      { title: 'Tribe Building Guide', slug: 'soulmask-tribe-guide', category: 'Guides', excerpt: 'Build and manage a tribe.' },
      { title: 'Base Building Tips', slug: 'soulmask-base-building', category: 'Guides', excerpt: 'Defense layouts.' },
      { title: 'Best Weapons', slug: 'soulmask-best-weapons', category: 'Weapons', excerpt: 'Top weapons.' },
    ],
    categories: ['Build Guides', 'Boss Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides'],
  },
  {
    slug: 'dune-awakening',
    name: 'Dune: Awakening',
    category: 'Survival',
    emoji: '🏜️',
    image: 'https://cdn.akamai.steamstatic.com/steam/apps/2377360/header.jpg',
    developer: 'Funcom',
    publisher: 'Koch Media',
    releaseDate: '2025',
    genres: ['Survival', 'Open World', 'Sandbox', 'Sci-Fi'],
    description: 'Dune: Awakening is an open-world survival MMO set on the harsh desert planet of Arrakis. Harvest Spice and survive.',
    metaTitle: 'Dune: Awakening Guide, Spice Farming & Base Building | Xavrito',
    metaDescription: 'Survive on Arrakis with guides on Spice harvesting, base building, and Sandworm encounters.',
    featuredGuides: [
      { title: 'Spice Farming Guide', slug: 'dune-awakening-spice-farming', category: 'Resources', excerpt: 'Efficient Spice routes.' },
      { title: 'Base Building Guide', slug: 'dune-awakening-base-building', category: 'Guides', excerpt: 'Secure your base.' },
      { title: 'Sandworm Encounters', slug: 'dune-awakening-sandworms', category: 'Guides', excerpt: 'How to survive Sandworms.' },
      { title: 'Faction Guide', slug: 'dune-awakening-factions', category: 'Guides', excerpt: 'Navigate politics.' },
    ],
    categories: ['Build Guides', 'Crafting', 'Weapons', 'Armor', 'Maps', 'Resources', 'Quests', 'Beginner Guides', 'Codes'],
  },
  {
    slug: 'abiotic-factor',
    name: 'Abiotic Factor',
    category: 'Puzzle',
    emoji: '🔬',
    image: 'https://www.abioticfactor.com/abiotic-factor.jpg',
    developer: 'dee我们是游戏',
    publisher: 'PubSelect',
    releaseDate: '2024',
    genres: ['Puzzle', 'Co-op', 'Adventure', 'Sci-Fi'],
    description: 'Abiotic Factor is a co-op puzzle adventure game. Explore an abandoned research facility and solve creative puzzles.',
    metaTitle: 'Abiotic Factor Guide, Puzzle Solutions & Tips | Xavrito',
    metaDescription: 'Complete Abiotic Factor puzzle solutions, item locations, department guide, and co-op tips.',
    featuredGuides: [
      { title: 'Puzzle Solutions Guide', slug: 'abiotic-factor-puzzle-solutions', category: 'Guides', excerpt: 'Solutions to every puzzle.' },
      { title: 'Item Locations', slug: 'abiotic-factor-item-locations', category: 'Resources', excerpt: 'Where to find key items.' },
      { title: 'Department Guide', slug: 'abiotic-factor-department-guide', category: 'Guides', excerpt: 'Walkthrough for each area.' },
      { title: 'Co-op Tips', slug: 'abiotic-factor-coop-tips', category: 'Guides', excerpt: 'Maximize efficiency.' },
    ],
    categories: ['Guides', 'Maps', 'Resources', 'Achievements', 'Beginner Guides'],
  },

  // === EXTERNAL/PARTNER GAMES ===
  {
    slug: 'solateria',
    name: 'Solateria',
    category: 'Metroidvania',
    emoji: '✨',
    image: 'https://shared.cdn.queniuqe.com/store_item_assets/steam/apps/2593450/capsule_616x353.jpg',
    external: 'https://solateria.com',
    developer: 'Studio Doodal',
    releaseDate: '2025',
    genres: ['Metroidvania', 'Soulslike', 'Action'],
    description: 'Solateria is a Metroidvania with parry and counter combat mechanics.',
    metaTitle: 'Solateria Guide, Boss Strategies & Parts Builds | Xavrito',
    metaDescription: 'Complete Solateria strategy guide with boss fight strategies and optimal parts builds.',
  },
  {
    slug: 'rift-wizard-3',
    name: 'Rift Wizard 3',
    category: 'Roguelike',
    emoji: '🧙',
    image: 'https://shared.cdn.queniuqe.com/store_item_assets/steam/apps/4366330/a649d17e02abdb81268978d65927947b5b079953/capsule_616x353.jpg',
    external: 'https://riftwizard3.com',
    developer: 'Dylan White',
    releaseDate: '2026',
    genres: ['Roguelike', 'Dungeon Crawler', 'Spell Casting'],
    description: 'Rift Wizard 3 is a roguelike wizard game focused on spell crafting.',
    metaTitle: 'Rift Wizard 3 Guide, Best Builds & Crafting Recipes | Xavrito',
    metaDescription: 'The definitive Rift Wizard 3 fan hub with spell builds and crafting recipes.',
  },
]

export const categories = [
  'Build Guides',
  'Tier Lists',
  'Boss Guides',
  'Crafting',
  'Weapons',
  'Armor',
  'Maps',
  'Resources',
  'Quests',
  'Beginner Guides',
  'Achievements',
  'Codes',
  'Patch Notes'
]

export function getGameBySlug(slug: string): Game | undefined {
  return games.find(g => g.slug === slug)
}

export function getGamesByCategory(category: string): Game[] {
  return games.filter(g => g.categories?.includes(category))
}
