export interface Html5Game {
  slug: string
  name: string
  category: string
  emoji: string
  thumbnail: string
  gameUrl: string
  developer?: string
  description: string
  controls?: string
  tags: string[]
  featured?: boolean
}

export const categories = [
  'All',
  'Puzzle',
  'Action',
  'Arcade',
  'Racing',
  'Sports',
  'Simulation',
  'Memory',
  'Stickman',
  'Kids',
]

export const html5Games: Html5Game[] = [
  // === FEATURED (Top Quality) ===
  {
    slug: 'prism-match-3d',
    name: 'Prism Match 3D',
    category: 'Puzzle',
    emoji: '💎',
    thumbnail: 'https://img.gamepix.com/games/prism-match-3d/cover/prism-match-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/prism-match-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Rotate cubes in a 3D prism world. Match colors by视角切换，找到相同颜色的方块。简单到爆，但停不下来。',
    controls: 'Click and drag to rotate the cube',
    tags: ['match-3', '3d', 'relaxing'],
    featured: true,
  },
  {
    slug: 'merge-royal',
    name: 'Merge Royal',
    category: 'Puzzle',
    emoji: '🃏',
    thumbnail: 'https://img.gamepix.com/games/merge-royal/cover/merge-royal.png?w=400',
    gameUrl: 'https://play.gamepix.com/merge-royal/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Solitaire meets 2048. 合并相同数字的卡牌，叠加到2048。纸牌+数字合成，双重上瘾。',
    controls: 'Click cards to move and merge',
    tags: ['2048', 'solitaire', 'merge'],
  },
  {
    slug: 'war-the-knights',
    name: 'War the Knights',
    category: 'Action',
    emoji: '⚔️',
    thumbnail: 'https://img.gamepix.com/games/war-the-knights/cover/war-the-knights.png?w=400',
    gameUrl: 'https://play.gamepix.com/war-the-knights/embed?sid=7O017',
    developer: 'GamePix',
    description: '骑士对战战场。排兵布阵，策略为王。兵种相克，以少胜多。',
    controls: 'Click to deploy units',
    tags: ['battle', 'strategy', 'knights'],
  },
  {
    slug: 'bus-driver-simulator-3d',
    name: 'Bus Driver Simulator 3D',
    category: 'Simulation',
    emoji: '🚌',
    thumbnail: 'https://img.gamepix.com/games/bus-driver-simulator-3d/cover/bus-driver-simulator-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/bus-driver-simulator-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: '城市公交模拟器。穿梭大街小巷，准时到站，安全第一。',
    controls: 'WASD or arrow keys to drive',
    tags: ['simulation', 'driving', '3d'],
  },
  {
    slug: 'three-cups-game',
    name: 'Three Cups Game',
    category: 'Memory',
    emoji: '🥤',
    thumbnail: 'https://img.gamepix.com/games/three-cups-game/cover/three-cups-game.png?w=400',
    gameUrl: 'https://play.gamepix.com/three-cups-game/embed?sid=7O017',
    developer: 'GamePix',
    description: '经典杯子游戏。追踪藏在杯子下的东西。集中注意力，挑战记忆极限。',
    controls: 'Click to guess cup location',
    tags: ['memory', 'guess', 'classic'],
  },
  {
    slug: 'body-drop-3d',
    name: 'Body Drop 3D',
    category: 'Simulation',
    emoji: '🎯',
    thumbnail: 'https://img.gamepix.com/games/body-drop-3d/cover/body-drop-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/body-drop-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: '用有限的球制造最大破坏。物理碰撞，布娃娃坠落，笑点满满。',
    controls: 'Click to aim and shoot',
    tags: ['simulation', 'physics', 'ragdoll'],
  },
  {
    slug: 'parmesan-partisan',
    name: 'Parmesan Partisan',
    category: 'Arcade',
    emoji: '🧀',
    thumbnail: 'https://img.gamepix.com/games/parmesan-partisan/cover/parmesan-partisan.png?w=400',
    gameUrl: 'https://play.gamepix.com/parmesan-partisan/embed?sid=7O017',
    developer: 'GamePix',
    description: '保护你的芝士城堡！霰弹枪射老鼠，可爱又疯狂的塔防射击。',
    controls: 'Mouse to aim, click to shoot',
    tags: ['arcade', 'defense', 'shooting'],
  },
  {
    slug: 'kobadoo-emojis',
    name: 'Kobadoo Emojis',
    category: 'Memory',
    emoji: '😀',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-emojis/cover/kobadoo-emojis.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-emojis/embed?sid=7O017',
    developer: 'GamePix',
    description: '记住emoji表情顺序。越来越长的序列，越来越难的挑战。',
    controls: 'Click emojis in order',
    tags: ['memory', 'emoji', 'sequence'],
  },
  {
    slug: 'hoops-and-fruits',
    name: 'Hoops & Fruits',
    category: 'Puzzle',
    emoji: '🏀',
    thumbnail: 'https://img.gamepix.com/games/hoops-and-fruits/cover/hoops-and-fruits.png?w=400',
    gameUrl: 'https://play.gamepix.com/hoops-and-fruits/embed?sid=7O017',
    developer: 'GamePix',
    description: '把球扔进篮筐，同时穿过水果。一石二鸟，精准投掷。',
    controls: 'Click and drag to aim and throw',
    tags: ['drawing', 'physics', 'fruit-ninja'],
  },
  {
    slug: 'turbo-crash-test',
    name: 'Turbo Crash Test',
    category: 'Stickman',
    emoji: '💥',
    thumbnail: 'https://img.gamepix.com/games/turbo-dismounting/cover/turbo-dismounting.png?w=400',
    gameUrl: 'https://play.gamepix.com/turbo-dismounting/embed?sid=7O017',
    developer: 'GamePix',
    description: '布娃娃物理碰撞游戏。制造最疯狂的撞击，欣赏最滑稽的翻滚。',
    controls: 'Click obstacles to trigger crashes',
    tags: ['stickman', 'physics', 'crash'],
  },
  {
    slug: 'cerkio',
    name: 'Cerkio',
    category: 'Arcade',
    emoji: '🎯',
    thumbnail: 'https://img.gamepix.com/games/cerkio/cover/cerkio.png?w=400',
    gameUrl: 'https://play.gamepix.com/cerkio/embed?sid=7O017',
    developer: 'GamePix',
    description: '一指尖投球，命中目标。30个关卡，简单的操作，不简单的精准。',
    controls: 'Click to throw ball',
    tags: ['ball', 'accuracy', 'one-touch'],
  },
  {
    slug: 'gelatino',
    name: 'Gelatino',
    category: 'Arcade',
    emoji: '🍦',
    thumbnail: 'https://img.gamepix.com/games/gelatino/cover/gelatino.png?w=400',
    gameUrl: 'https://play.gamepix.com/gelatino/embed?sid=7O017',
    developer: 'GamePix',
    description: '冰棒大冒险。摆动躲避障碍，收集冰块，别融化！',
    controls: 'Click to swing',
    tags: ['arcade', 'timing', 'swing'],
  },
  {
    slug: 'penalty-kick-wiz',
    name: 'Penalty Kick Wiz',
    category: 'Sports',
    emoji: '⚽',
    thumbnail: 'https://img.gamepix.com/games/penalty-kick-wiz/cover/penalty-kick-wiz.png?w=400',
    gameUrl: 'https://play.gamepix.com/penalty-kick-wiz/embed?sid=7O017',
    developer: 'GamePix',
    description: '点球大战。守门员 vs 任意球大师。每一个进球都令人窒息。',
    controls: 'Swipe to shoot',
    tags: ['sports', 'soccer', 'penalty'],
  },
  {
    slug: 'merge-mine-idle-clicker',
    name: 'Merge Mine',
    category: 'Puzzle',
    emoji: '⛏️',
    thumbnail: 'https://img.gamepix.com/games/merge-mine/cover/merge-mine.png?w=400',
    gameUrl: 'https://play.gamepix.com/merge-mine/embed?sid=7O017',
    developer: 'GamePix',
    description: '合并矿石，升级矿山。点击即玩，挂机也能变富。',
    controls: 'Click to mine, drag to merge',
    tags: ['merge', 'idle', 'clicker'],
  },
  {
    slug: 'stickman-warriors',
    name: 'Stickman Warriors',
    category: 'Stickman',
    emoji: '🦸',
    thumbnail: 'https://img.gamepix.com/games/stickman-warriors/cover/stickman-warriors.png?w=400',
    gameUrl: 'https://play.gamepix.com/stickman-warriors/embed?sid=7O017',
    developer: 'GamePix',
    description: '火柴人技能大战。连击、必杀技、华丽的战斗效果。',
    controls: 'Click to attack, swipe for combos',
    tags: ['stickman', 'fighting', 'action'],
  },
  {
    slug: 'kobadoo-numbers',
    name: 'Kobadoo Numbers',
    category: 'Memory',
    emoji: '🔢',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-numbers/cover/kobadoo-numbers.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-numbers/embed?sid=7O017',
    developer: 'GamePix',
    description: '记住数字序列。数字越来越长，你的脑细胞在燃烧吗？',
    controls: 'Click numbers in order',
    tags: ['memory', 'numbers', 'sequence'],
  },
  {
    slug: 'flamit',
    name: 'Flamit',
    category: 'Action',
    emoji: '🔥',
    thumbnail: 'https://img.gamepix.com/games/flamit/cover/flamit.png?w=400',
    gameUrl: 'https://play.gamepix.com/flamit/embed?sid=7O017',
    developer: 'GamePix',
    description: '火焰小人跑酷。跳跃、冲刺、躲避障碍。永不熄灭。',
    controls: 'Tap or click to jump',
    tags: ['adventure', 'runner', 'fire'],
  },
  {
    slug: 'stickman-street-fighting-3d',
    name: 'Stickman Street Fighting 3D',
    category: 'Stickman',
    emoji: '👊',
    thumbnail: 'https://img.gamepix.com/games/stickman-street-fighting-3d/cover/stickman-street-fighting-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/stickman-street-fighting-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: '街头格斗3D。拳击、踢腿、组合技。成为最狠的火柴人。',
    controls: 'Tap to punch/kick, swipe to dodge',
    tags: ['stickman', 'fighting', '3d'],
  },
  {
    slug: 'morphit',
    name: 'Morphit',
    category: 'Puzzle',
    emoji: '🟦',
    thumbnail: 'https://img.gamepix.com/games/morphit/cover/morphit.png?w=400',
    gameUrl: 'https://play.gamepix.com/morphit/embed?sid=7O017',
    developer: 'GamePix',
    description: '改变形状穿过障碍。灵活变通，方块也能走天下。',
    controls: 'Drag to morph shape',
    tags: ['puzzle', 'shapes', 'morph'],
  },
  {
    slug: 'robot-band-find-differences',
    name: 'Robot Band',
    category: 'Puzzle',
    emoji: '🤖',
    thumbnail: 'https://img.gamepix.com/games/robot-band/cover/robot-band.png?w=400',
    gameUrl: 'https://play.gamepix.com/robot-band/embed?sid=7O017',
    developer: 'GamePix',
    description: '找出两图不同。机器人乐队主题，发现细微差别。',
    controls: 'Click on differences',
    tags: ['puzzle', 'difference', 'robots'],
  },
  {
    slug: 'my-first-100-words',
    name: 'My First 100 Words',
    category: 'Kids',
    emoji: '📚',
    thumbnail: 'https://img.gamepix.com/games/my-first-100-words/cover/my-first-100-words.png?w=400',
    gameUrl: 'https://play.gamepix.com/my-first-100-words/embed?sid=7O017',
    developer: 'GamePix',
    description: '学100个单词。图画配单词，轻松学英语。',
    controls: 'Click on matching words',
    tags: ['educational', 'words', 'kids'],
  },
  {
    slug: 'sokoballs',
    name: 'Sokoballs',
    category: 'Puzzle',
    emoji: '🧩',
    thumbnail: 'https://img.gamepix.com/games/sokoballs/cover/sokoballs.png?w=400',
    gameUrl: 'https://play.gamepix.com/sokoballs/embed?sid=7O017',
    developer: 'GamePix',
    description: '推球入洞。物理益智，思考每一步，球会滚向哪里？',
    controls: 'Click to shoot ball',
    tags: ['puzzle', 'physics', 'ball'],
  },
  {
    slug: 'going-right',
    name: 'Going Right',
    category: 'Action',
    emoji: '➡️',
    thumbnail: 'https://img.gamepix.com/games/going-right/cover/going-right.png?w=400',
    gameUrl: 'https://play.gamepix.com/going-right/embed?sid=7O017',
    developer: 'GamePix',
    description: '只能往右走。收集金币，躲避障碍。简单方向，无限可能。',
    controls: 'Tap to jump',
    tags: ['endless', 'runner', 'simple'],
  },
  {
    slug: 'funny-shooter-2',
    name: 'Funny Shooter 2',
    category: 'Action',
    emoji: '🔫',
    thumbnail: 'https://img.gamepix.com/games/funny-shooter-2/cover/funny-shooter-2.png?w=400',
    gameUrl: 'https://play.gamepix.com/funny-shooter-2/embed?sid=7O017',
    developer: 'GamePix',
    description: '射击怪物，笑着打。奇葩武器，滑稽敌人，越打越欢乐。',
    controls: 'Mouse to aim, click to shoot',
    tags: ['shooter', 'zombie', 'funny'],
  },
  {
    slug: 'canjump',
    name: 'Canjump',
    category: 'Action',
    emoji: '🦘',
    thumbnail: 'https://img.gamepix.com/games/canjump/cover/canjump.png?w=400',
    gameUrl: 'https://play.gamepix.com/canjump/embed?sid=7O017',
    developer: 'GamePix',
    description: '跳跳跳跃。踩着方块往上跳，能跳多高？',
    controls: 'Click to jump',
    tags: ['platformer', 'jumping', 'vertical'],
  },
  {
    slug: 'moto-x3m-spooky',
    name: 'Moto X3M Spooky',
    category: 'Racing',
    emoji: '🏍️',
    thumbnail: 'https://img.gamepix.com/games/moto-x3m-spooky-land/cover/moto-x3m-spooky-land.png?w=400',
    gameUrl: 'https://play.gamepix.com/moto-x3m-spooky-land/embed?sid=7O017',
    developer: 'GamePix',
    description: '摩托车越野挑战。翻跟头、空中花式、躲避障碍。万圣节特别版。',
    controls: 'Arrow keys to balance and accelerate',
    tags: ['racing', 'motorcycle', 'physics'],
  },
  {
    slug: 'slope-racing-3d',
    name: 'Slope Racing 3D',
    category: 'Racing',
    emoji: '🎿',
    thumbnail: 'https://img.gamepix.com/games/slope-racing-3d/cover/slope-racing-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/slope-racing-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: '雪地斜坡赛车。控制速度，不要飞出去。',
    controls: 'Arrow keys to control',
    tags: ['racing', '3d', 'slope'],
  },
  {
    slug: 'tentrix',
    name: 'TenTrix',
    category: 'Puzzle',
    emoji: '🧱',
    thumbnail: 'https://img.gamepix.com/games/tentrix/cover/tentrix.png?w=400',
    gameUrl: 'https://play.gamepix.com/tentrix/embed?sid=7O017',
    developer: 'GamePix',
    description: '俄罗斯方块进化版。组合方块，填满行。经典重制。',
    controls: 'Arrow keys to move and rotate',
    tags: ['tetris', 'block', 'puzzle'],
  },
  {
    slug: 'kobadoo-shapes',
    name: 'Kobadoo Shapes',
    category: 'Memory',
    emoji: '🔷',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-shapes/cover/kobadoo-shapes.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-shapes/embed?sid=7O017',
    developer: 'GamePix',
    description: '记住形状顺序。越来越复杂的图形，挑战你的短期记忆。',
    controls: 'Click shapes in order',
    tags: ['memory', 'shapes', 'sequence'],
  },
  {
    slug: 'royal-couple-halloween',
    name: 'Royal Couple Halloween',
    category: 'Kids',
    emoji: '👻',
    thumbnail: 'https://img.gamepix.com/games/royal-couple-halloween-party/cover/royal-couple-halloween-party.png?w=400',
    gameUrl: 'https://play.gamepix.com/royal-couple-halloween-party/embed?sid=7O017',
    developer: 'GamePix',
    description: '王子公主万圣节换装。选服装、化妆、派对开始！',
    controls: 'Click to dress up',
    tags: ['dress-up', 'halloween', 'kids'],
  },

  // === MORE HIGH QUALITY GAMES ===
  {
    slug: 'ten-balls',
    name: 'Ten Balls',
    category: 'Arcade',
    emoji: '🔵',
    thumbnail: 'https://img.gamepix.com/games/ten-balls/cover/ten-balls.png?w=400',
    gameUrl: 'https://play.gamepix.com/ten-balls/embed?sid=7O017',
    developer: 'GamePix',
    description: '十颗球，精准射击。物理弹射，撞更多球得分。',
    controls: 'Click and drag to aim',
    tags: ['ball', 'shooting', 'physics'],
  },
  {
    slug: 'draw-and-erase',
    name: 'Draw and Erase',
    category: 'Puzzle',
    emoji: '✏️',
    thumbnail: 'https://img.gamepix.com/games/draw-and-erase/cover/draw-and-erase.png?w=400',
    gameUrl: 'https://play.gamepix.com/draw-and-erase/embed?sid=7O017',
    developer: 'GamePix',
    description: '画条线引导球。物理谜题，发挥创意解决问题。',
    controls: 'Draw lines with mouse',
    tags: ['drawing', 'physics', 'puzzle'],
  },
  {
    slug: 'fill-the-glass',
    name: 'Fill the Glass',
    category: 'Puzzle',
    emoji: '🥛',
    thumbnail: 'https://img.gamepix.com/games/fill-the-glass/cover/fill-the-glass.png?w=400',
    gameUrl: 'https://play.gamepix.com/fill-the-glass/embed?sid=7O017',
    developer: 'GamePix',
    description: '倒水填满杯子。角度、液体物理，精确控制。',
    controls: 'Click and hold to pour',
    tags: ['puzzle', 'physics', 'water'],
  },
  {
    slug: 'spin-perfect',
    name: 'Spin Perfect',
    category: 'Arcade',
    emoji: '🎡',
    thumbnail: 'https://img.gamepix.com/games/spin-perfect/cover/spin-perfect.png?w=400',
    gameUrl: 'https://play.gamepix.com/spin-perfect/embed?sid=7O017',
    developer: 'GamePix',
    description: '旋转命中目标。控制旋转角度，一击入魂。',
    controls: 'Click to set angle and shoot',
    tags: ['arcade', 'aiming', 'timing'],
  },
  {
    slug: 'zombie-survivor',
    name: 'Zombie Survivor',
    category: 'Action',
    emoji: '🧟',
    thumbnail: 'https://img.gamepix.com/games/zombie-survivor/cover/zombie-survivor.png?w=400',
    gameUrl: 'https://play.gamepix.com/zombie-survivor/embed?sid=7O017',
    developer: 'GamePix',
    description: '僵尸围城，生存到最后。升级武器，抵御尸潮。',
    controls: 'Click to shoot',
    tags: ['zombie', 'survival', 'shooter'],
  },
  {
    slug: 'rope-unfriendly',
    name: 'Rope Unfriendly',
    category: 'Puzzle',
    emoji: '🪢',
    thumbnail: 'https://img.gamepix.com/games/rope-unfriendly/cover/rope-unfriendly.png?w=400',
    gameUrl: 'https://play.gamepix.com/rope-unfriendly/embed?sid=7O017',
    developer: 'GamePix',
    description: '解开绳结。逻辑推理，步骤正确才能解开。',
    controls: 'Click ropes to untangle',
    tags: ['puzzle', 'logic', 'rope'],
  },
  {
    slug: 'pin-balls',
    name: 'Pin Balls',
    category: 'Arcade',
    emoji: '🎳',
    thumbnail: 'https://img.gamepix.com/games/pin-balls/cover/pin-balls.png?w=400',
    gameUrl: 'https://play.gamepix.com/pin-balls/embed?sid=7O017',
    developer: 'GamePix',
    description: '弹珠台。撞击球瓶，全中加分。经典街机风。',
    controls: 'Click to launch ball',
    tags: ['pinball', 'arcade', 'classic'],
  },
  {
    slug: 'pool-8-ball',
    name: '8 Ball Pool',
    category: 'Sports',
    emoji: '🎱',
    thumbnail: 'https://img.gamepix.com/games/pool-8-ball/cover/pool-8-ball.png?w=400',
    gameUrl: 'https://play.gamepix.com/pool-8-ball/embed?sid=7O017',
    developer: 'GamePix',
    description: '8球台球。瞄准、发力、进洞。台球高手就是你。',
    controls: 'Click and drag to aim and shoot',
    tags: ['pool', 'sports', 'billiards'],
  },
  {
    slug: 'candy-bubble',
    name: 'Candy Bubble',
    category: 'Puzzle',
    emoji: '🍬',
    thumbnail: 'https://img.gamepix.com/games/candy-bubble/cover/candy-bubble.png?w=400',
    gameUrl: 'https://play.gamepix.com/candy-bubble/embed?sid=7O017',
    developer: 'GamePix',
    description: '泡泡龙糖果版。相同颜色泡泡，连接消除。甜蜜消消乐。',
    controls: 'Mouse to aim, click to shoot',
    tags: ['bubble-shooter', 'match-3', 'candy'],
  },
  {
    slug: 'speak-easy',
    name: 'Speak Easy',
    category: 'Kids',
    emoji: '🗣️',
    thumbnail: 'https://img.gamepix.com/games/speak-easy/cover/speak-easy.png?w=400',
    gameUrl: 'https://play.gamepix.com/speak-easy/embed?sid=7O017',
    developer: 'GamePix',
    description: '跟读练习英语。录音、对比、纠正发音。',
    controls: 'Click microphone to record',
    tags: ['english', 'speaking', 'educational'],
  },
  {
    slug: 'shooting-classics',
    name: 'Shooting Classics',
    category: 'Action',
    emoji: '🔫',
    thumbnail: 'https://img.gamepix.com/games/shooting-classics/cover/shooting-classics.png?w=400',
    gameUrl: 'https://play.gamepix.com/shooting-classics/embed?sid=7O017',
    developer: 'GamePix',
    description: '经典射击合集。瞄准、射击、得分。靶场练兵。',
    controls: 'Mouse to aim, click to shoot',
    tags: ['shooting', 'aim', 'target'],
  },
  {
    slug: 'knife-target',
    name: 'Knife Target',
    category: 'Arcade',
    emoji: '🔪',
    thumbnail: 'https://img.gamepix.com/games/knife-target/cover/knife-target.png?w=400',
    gameUrl: 'https://play.gamepix.com/knife-target/embed?sid=7O017',
    developer: 'GamePix',
    description: '飞刀投掷。精准命中红心，每一刀都要准。',
    controls: 'Click to throw knife',
    tags: ['knife', 'throwing', 'accuracy'],
  },
  {
    slug: 'stack-balls-3d',
    name: 'Stack Balls 3D',
    category: 'Arcade',
    emoji: '🟢',
    thumbnail: 'https://img.gamepix.com/games/stack-balls-3d/cover/stack-balls-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/stack-balls-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: '堆球下落。相同颜色穿过，不同颜色堆叠。挑战极限高度。',
    controls: 'Tap to switch color',
    tags: ['stack', '3d', 'color-matching'],
  },
  {
    slug: 'cut-the-rope',
    name: 'Cut the Rope',
    category: 'Puzzle',
    emoji: '🍬',
    thumbnail: 'https://img.gamepix.com/games/cut-the-rope/cover/cut-the-rope.png?w=400',
    gameUrl: 'https://play.gamepix.com/cut-the-rope/embed?sid=7O017',
    developer: 'GamePix',
    description: ' Om Nom 吃糖。切断绳子，让糖果掉进嘴里。物理解谜经典。',
    controls: 'Click to cut ropes',
    tags: ['physics', 'puzzle', 'cut-rope'],
  },
  {
    slug: 'temple-berry',
    name: 'Temple Berry',
    category: 'Action',
    emoji: '🍓',
    thumbnail: 'https://img.gamepix.com/games/temple-berry/cover/temple-berry.png?w=400',
    gameUrl: 'https://play.gamepix.com/temple-berry/embed?sid=7O017',
    developer: 'GamePix',
    description: '神庙跑酷收集草莓。跑、跳、躲障碍。甜蜜奔跑。',
    controls: 'Tap to jump',
    tags: ['runner', 'temple', 'collect'],
  },
  {
    slug: 'soccer-kicks-3d',
    name: 'Soccer Kicks 3D',
    category: 'Sports',
    emoji: '⚽',
    thumbnail: 'https://img.gamepix.com/games/soccer-kicks-3d/cover/soccer-kicks-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/soccer-kicks-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: '3D任意球挑战。角度、弧线、力度。成为任意球大师。',
    controls: 'Swipe to shoot',
    tags: ['soccer', '3d', 'free-kick'],
  },
  {
    slug: 'darts-pro',
    name: 'Darts Pro',
    category: 'Sports',
    emoji: '🎯',
    thumbnail: 'https://img.gamepix.com/games/darts-pro/cover/darts-pro.png?w=400',
    gameUrl: 'https://play.gamepix.com/darts-pro/embed?sid=7O017',
    developer: 'GamePix',
    description: '飞镖高手。瞄准红心，计算风速，一镖定乾坤。',
    controls: 'Click and drag to throw',
    tags: ['darts', 'aim', 'precision'],
  },
  {
    slug: 'bottle-flip-challenge',
    name: 'Bottle Flip Challenge',
    category: 'Arcade',
    emoji: '🍾',
    thumbnail: 'https://img.gamepix.com/games/bottle-flip-challenge/cover/bottle-flip-challenge.png?w=400',
    gameUrl: 'https://play.gamepix.com/bottle-flip-challenge/embed?sid=7O017',
    developer: 'GamePix',
    description: '水瓶翻转挑战。翻瓶成功着陆，抖音最火游戏。',
    controls: 'Click or space to flip',
    tags: ['flip', 'bottle', 'timing'],
  },
  {
    slug: 'fruit-ninja- slice',
    name: 'Fruit Ninja',
    category: 'Action',
    emoji: '🍉',
    thumbnail: 'https://img.gamepix.com/games/fruit-ninja/cover/fruit-ninja.png?w=400',
    gameUrl: 'https://play.gamepix.com/fruit-ninja/embed?sid=7O017',
    developer: 'GamePix',
    description: '切水果。滑动刀锋，切切切！忍者刀法修炼场。',
    controls: 'Swipe to cut',
    tags: ['fruit-ninja', 'slice', 'swipe'],
  },
  {
    slug: 'bricks-breaker',
    name: 'Bricks Breaker',
    category: 'Puzzle',
    emoji: '🧱',
    thumbnail: 'https://img.gamepix.com/games/bricks-breaker/cover/bricks-breaker.png?w=400',
    gameUrl: 'https://play.gamepix.com/bricks-breaker/embed?sid=7O017',
    developer: 'GamePix',
    description: '打砖块。弹球击砖，经典重现。一球通关可能吗？',
    controls: 'Mouse to move paddle',
    tags: ['arkanoid', 'brick-breaker', 'classic'],
  },
]

export function getGameBySlug(slug: string): Html5Game | undefined {
  return html5Games.find(g => g.slug === slug)
}

export function getFeaturedGame(): Html5Game | undefined {
  return html5Games.find(g => g.featured)
}

export function getGamesByCategory(category: string): Html5Game[] {
  if (category === 'All') return html5Games
  return html5Games.filter(g => g.category === category)
}

export function getRelatedGames(game: Html5Game, limit = 4): Html5Game[] {
  return html5Games
    .filter(g => g.slug !== game.slug && g.category === game.category)
    .slice(0, limit)
}
