export interface Html5Game {
  slug: string
  name: string
  category: string
  emoji: string
  thumbnail: string
  gameUrl: string
  developer?: string
  description: string
  controls?: string
  tags: string[]
  featured?: boolean
}

export const categories = [
  'All',
  'Puzzle',
  'Action',
  'Arcade',
  'Racing',
  'Sports',
  'Simulation',
  'Memory',
  'Stickman',
  'Kids',
]

export const html5Games: Html5Game[] = [
  // === FEATURED (Top Quality) ===
  {
    slug: 'prism-match-3d',
    name: 'Prism Match 3D',
    category: 'Puzzle',
    emoji: '💎',
    thumbnail: 'https://img.gamepix.com/games/prism-match-3d/cover/prism-match-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/prism-match-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Rotate 3D cubes to match colors. Simple concept, addictive gameplay. Can you clear all levels?',
    controls: 'Click and drag to rotate the cube',
    tags: ['match-3', '3d', 'relaxing'],
    featured: true,
  },
  {
    slug: 'merge-royal',
    name: 'Merge Royal',
    category: 'Puzzle',
    emoji: '🃏',
    thumbnail: 'https://img.gamepix.com/games/merge-royal/cover/merge-royal.png?w=400',
    gameUrl: 'https://play.gamepix.com/merge-royal/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Solitaire meets 2048. Merge cards to reach 2048. Two classics, one game.',
    controls: 'Click cards to move and merge',
    tags: ['2048', 'solitaire', 'merge'],
  },
  {
    slug: 'war-the-knights',
    name: 'War the Knights',
    category: 'Action',
    emoji: '⚔️',
    thumbnail: 'https://img.gamepix.com/games/war-the-knights/cover/war-the-knights.png?w=400',
    gameUrl: 'https://play.gamepix.com/war-the-knights/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Deploy knights and win the battle. Strategy meets action. Outsmart your opponent.',
    controls: 'Click to deploy units',
    tags: ['battle', 'strategy', 'knights'],
  },
  {
    slug: 'bus-driver-simulator-3d',
    name: 'Bus Driver Simulator 3D',
    category: 'Simulation',
    emoji: '🚌',
    thumbnail: 'https://img.gamepix.com/games/bus-driver-simulator-3d/cover/bus-driver-simulator-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/bus-driver-simulator-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Be a bus driver. Navigate city streets, pick up passengers, and deliver them safely.',
    controls: 'WASD or arrow keys to drive',
    tags: ['simulation', 'driving', '3d'],
  },
  {
    slug: 'three-cups-game',
    name: 'Three Cups Game',
    category: 'Memory',
    emoji: '🥤',
    thumbnail: 'https://img.gamepix.com/games/three-cups-game/cover/three-cups-game.png?w=400',
    gameUrl: 'https://play.gamepix.com/three-cups-game/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Classic shell game. Track the ball under the cups. How sharp is your eye?',
    controls: 'Click to guess cup location',
    tags: ['memory', 'guess', 'classic'],
  },
  {
    slug: 'body-drop-3d',
    name: 'Body Drop 3D',
    category: 'Simulation',
    emoji: '🎯',
    thumbnail: 'https://img.gamepix.com/games/body-drop-3d/cover/body-drop-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/body-drop-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Launch crash test dummies and watch the ragdoll physics. Maximize damage with limited balls.',
    controls: 'Click to aim and shoot',
    tags: ['simulation', 'physics', 'ragdoll'],
  },
  {
    slug: 'parmesan-partisan',
    name: 'Parmesan Partisan',
    category: 'Arcade',
    emoji: '🧀',
    thumbnail: 'https://img.gamepix.com/games/parmesan-partisan/cover/parmesan-partisan.png?w=400',
    gameUrl: 'https://play.gamepix.com/parmesan-partisan/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Defend your cheese castle from rats. Shotgun action meets tower defense.',
    controls: 'Mouse to aim, click to shoot',
    tags: ['arcade', 'defense', 'shooting'],
  },
  {
    slug: 'kobadoo-emojis',
    name: 'Kobadoo Emojis',
    category: 'Memory',
    emoji: '😀',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-emojis/cover/kobadoo-emojis.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-emojis/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Remember emoji sequences. Gets harder as sequences grow longer. Test your memory.',
    controls: 'Click emojis in order',
    tags: ['memory', 'emoji', 'sequence'],
  },
  {
    slug: 'hoops-and-fruits',
    name: 'Hoops & Fruits',
    category: 'Puzzle',
    emoji: '🏀',
    thumbnail: 'https://img.gamepix.com/games/hoops-and-fruits/cover/hoops-and-fruits.png?w=400',
    gameUrl: 'https://play.gamepix.com/hoops-and-fruits/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Throw balls through hoops to hit fruits. Physics-based puzzle meets Fruit Ninja.',
    controls: 'Click and drag to aim and throw',
    tags: ['drawing', 'physics', 'fruit-ninja'],
  },
  {
    slug: 'turbo-crash-test',
    name: 'Turbo Crash Test',
    category: 'Stickman',
    emoji: '💥',
    thumbnail: 'https://img.gamepix.com/games/turbo-dismounting/cover/turbo-dismounting.png?w=400',
    gameUrl: 'https://play.gamepix.com/turbo-dismounting/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Create epic crashes with ragdoll physics. Unlock vehicles and watch the chaos.',
    controls: 'Click obstacles to trigger crashes',
    tags: ['stickman', 'physics', 'crash'],
  },
  {
    slug: 'cerkio',
    name: 'Cerkio',
    category: 'Arcade',
    emoji: '🎯',
    thumbnail: 'https://img.gamepix.com/games/cerkio/cover/cerkio.png?w=400',
    gameUrl: 'https://play.gamepix.com/cerkio/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Launch a ball into the target. 30 levels of precision timing. One-touch gameplay.',
    controls: 'Click to throw ball',
    tags: ['ball', 'accuracy', 'one-touch'],
  },
  {
    slug: 'gelatino',
    name: 'Gelatino',
    category: 'Arcade',
    emoji: '🍦',
    thumbnail: 'https://img.gamepix.com/games/gelatino/cover/gelatino.png?w=400',
    gameUrl: 'https://play.gamepix.com/gelatino/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Swing a popsicle past traps. Collect ice cubes, dodge heat. Will you melt or prevail?',
    controls: 'Click to swing',
    tags: ['arcade', 'timing', 'swing'],
  },
  {
    slug: 'penalty-kick-wiz',
    name: 'Penalty Kick Wiz',
    category: 'Sports',
    emoji: '⚽',
    thumbnail: 'https://img.gamepix.com/games/penalty-kick-wiz/cover/penalty-kick-wiz.png?w=400',
    gameUrl: 'https://play.gamepix.com/penalty-kick-wiz/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Penalty shootout. Goalkeeper vs striker. Every goal is satisfying.',
    controls: 'Swipe to shoot',
    tags: ['sports', 'soccer', 'penalty'],
  },
  {
    slug: 'stickman-warriors',
    name: 'Stickman Warriors',
    category: 'Stickman',
    emoji: '🦸',
    thumbnail: 'https://img.gamepix.com/games/stickman-warriors/cover/stickman-warriors.png?w=400',
    gameUrl: 'https://play.gamepix.com/stickman-warriors/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Stickman combat with special moves. Combos, ultimates, and flashy effects.',
    controls: 'Click to attack, swipe for combos',
    tags: ['stickman', 'fighting', 'action'],
  },
  {
    slug: 'kobadoo-numbers',
    name: 'Kobadoo Numbers',
    category: 'Memory',
    emoji: '🔢',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-numbers/cover/kobadoo-numbers.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-numbers/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Remember number sequences. Longer sequences as you progress. Brain teaser.',
    controls: 'Click numbers in order',
    tags: ['memory', 'numbers', 'sequence'],
  },
  {
    slug: 'flamit',
    name: 'Flamit',
    category: 'Action',
    emoji: '🔥',
    thumbnail: 'https://img.gamepix.com/games/flamit/cover/flamit.png?w=400',
    gameUrl: 'https://play.gamepix.com/flamit/embed?sid=7O017',
    developer: 'GamePix',
    description: 'A flaming stickman running adventure. Jump, dash, survive. Never extinguish.',
    controls: 'Tap or click to jump',
    tags: ['adventure', 'runner', 'fire'],
  },
  {
    slug: 'stickman-street-fighting-3d',
    name: 'Stickman Street Fighting 3D',
    category: 'Stickman',
    emoji: '👊',
    thumbnail: 'https://img.gamepix.com/games/stickman-street-fighting-3d/cover/stickman-street-fighting-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/stickman-street-fighting-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: '3D street fighting. Punches, kicks, combos. Become the toughest stickman.',
    controls: 'Tap to punch/kick, swipe to dodge',
    tags: ['stickman', 'fighting', '3d'],
  },
  {
    slug: 'morphit',
    name: 'Morphit',
    category: 'Puzzle',
    emoji: '🟦',
    thumbnail: 'https://img.gamepix.com/games/morphit/cover/morphit.png?w=400',
    gameUrl: 'https://play.gamepix.com/morphit/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Morph shapes to pass obstacles. Adapt and transform. Flexible puzzle solving.',
    controls: 'Drag to morph shape',
    tags: ['puzzle', 'shapes', 'morph'],
  },
  {
    slug: 'robot-band-find-differences',
    name: 'Robot Band',
    category: 'Puzzle',
    emoji: '🤖',
    thumbnail: 'https://img.gamepix.com/games/robot-band/cover/robot-band.png?w=400',
    gameUrl: 'https://play.gamepix.com/robot-band/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Find the differences between two images. Robot band theme. Train your eye.',
    controls: 'Click on differences',
    tags: ['puzzle', 'difference', 'robots'],
  },
  {
    slug: 'my-first-100-words',
    name: 'My First 100 Words',
    category: 'Kids',
    emoji: '📚',
    thumbnail: 'https://img.gamepix.com/games/my-first-100-words/cover/my-first-100-words.png?w=400',
    gameUrl: 'https://play.gamepix.com/my-first-100-words/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Learn 100 words with pictures. Match words to images. Educational fun.',
    controls: 'Click on matching words',
    tags: ['educational', 'words', 'kids'],
  },
  {
    slug: 'sokoballs',
    name: 'Sokoballs',
    category: 'Puzzle',
    emoji: '🧩',
    thumbnail: 'https://img.gamepix.com/games/sokoballs/cover/sokoballs.png?w=400',
    gameUrl: 'https://play.gamepix.com/sokoballs/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Physics puzzle. Shoot balls into holes. Think before you shoot.',
    controls: 'Click to shoot ball',
    tags: ['puzzle', 'physics', 'ball'],
  },
  {
    slug: 'going-right',
    name: 'Going Right',
    category: 'Action',
    emoji: '➡️',
    thumbnail: 'https://img.gamepix.com/games/going-right/cover/going-right.png?w=400',
    gameUrl: 'https://play.gamepix.com/going-right/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Can only go right. Collect coins, avoid obstacles. Simple but challenging.',
    controls: 'Tap to jump',
    tags: ['endless', 'runner', 'simple'],
  },
  {
    slug: 'funny-shooter-2',
    name: 'Funny Shooter 2',
    category: 'Action',
    emoji: '🔫',
    thumbnail: 'https://img.gamepix.com/games/funny-shooter-2/cover/funny-shooter-2.png?w=400',
    gameUrl: 'https://play.gamepix.com/funny-shooter-2/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Shoot weird monsters with silly weapons. Zany enemies, laugh-out-loud action.',
    controls: 'Mouse to aim, click to shoot',
    tags: ['shooter', 'zombie', 'funny'],
  },
  {
    slug: 'canjump',
    name: 'Canjump',
    category: 'Action',
    emoji: '🦘',
    thumbnail: 'https://img.gamepix.com/games/canjump/cover/canjump.png?w=400',
    gameUrl: 'https://play.gamepix.com/canjump/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Jump on blocks to climb higher. How high can you go? Vertical platformer.',
    controls: 'Click to jump',
    tags: ['platformer', 'jumping', 'vertical'],
  },
  {
    slug: 'moto-x3m-spooky',
    name: 'Moto X3M Spooky',
    category: 'Racing',
    emoji: '🏍️',
    thumbnail: 'https://img.gamepix.com/games/moto-x3m-spooky-land/cover/moto-x3m-spooky-land.png?w=400',
    gameUrl: 'https://play.gamepix.com/moto-x3m-spooky-land/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Motorcycle stunts with flips and obstacles. Spooky halloween edition. Physics-based.',
    controls: 'Arrow keys to balance and accelerate',
    tags: ['racing', 'motorcycle', 'physics'],
  },
  {
    slug: 'slope-racing-3d',
    name: 'Slope Racing 3D',
    category: 'Racing',
    emoji: '🎿',
    thumbnail: 'https://img.gamepix.com/games/slope-racing-3d/cover/slope-racing-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/slope-racing-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: "Slope racing down snowy hills. Control speed, don't fly off. Adrenaline rush.",
    controls: 'Arrow keys to control',
    tags: ['racing', '3d', 'slope'],
  },
  {
    slug: 'tentrix',
    name: 'TenTrix',
    category: 'Puzzle',
    emoji: '🧱',
    thumbnail: 'https://img.gamepix.com/games/tentrix/cover/tentrix.png?w=400',
    gameUrl: 'https://play.gamepix.com/tentrix/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Tetris evolved. Fill rows to clear blocks. Classic with a modern twist.',
    controls: 'Arrow keys to move and rotate',
    tags: ['tetris', 'block', 'puzzle'],
  },
  {
    slug: 'kobadoo-shapes',
    name: 'Kobadoo Shapes',
    category: 'Memory',
    emoji: '🔷',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-shapes/cover/kobadoo-shapes.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-shapes/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Remember shape sequences. Complex patterns as you level up. Short-term memory training.',
    controls: 'Click shapes in order',
    tags: ['memory', 'shapes', 'sequence'],
  },
  {
    slug: 'royal-couple-halloween',
    name: 'Royal Couple Halloween',
    category: 'Kids',
    emoji: '👻',
    thumbnail: 'https://img.gamepix.com/games/royal-couple-halloween-party/cover/royal-couple-halloween-party.png?w=400',
    gameUrl: 'https://play.gamepix.com/royal-couple-halloween-party/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Dress up the royal couple for Halloween. Costumes, makeup, party time!',
    controls: 'Click to dress up',
    tags: ['dress-up', 'halloween', 'kids'],
  },
  {
    slug: 'pool-8-ball',
    name: '8 Ball Pool',
    category: 'Sports',
    emoji: '🎱',
    thumbnail: 'https://img.gamepix.com/games/pool-8-ball/cover/pool-8-ball.png?w=400',
    gameUrl: 'https://play.gamepix.com/pool-8-ball/embed?sid=7O017',
    developer: 'GamePix',
    description: '8 ball pool classic. Aim, shoot, pocket. Become a pool master.',
    controls: 'Click and drag to aim and shoot',
    tags: ['pool', 'sports', 'billiards'],
  },
  {
    slug: 'candy-bubble',
    name: 'Candy Bubble',
    category: 'Puzzle',
    emoji: '🍬',
    thumbnail: 'https://img.gamepix.com/games/candy-bubble/cover/candy-bubble.png?w=400',
    gameUrl: 'https://play.gamepix.com/candy-bubble/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Bubble shooter with candy theme. Match colors, clear bubbles. Sweet puzzler.',
    controls: 'Mouse to aim, click to shoot',
    tags: ['bubble-shooter', 'match-3', 'candy'],
  },
  {
    slug: 'cut-the-rope',
    name: 'Cut the Rope',
    category: 'Puzzle',
    emoji: '🍬',
    thumbnail: 'https://img.gamepix.com/games/cut-the-rope/cover/cut-the-rope.png?w=400',
    gameUrl: 'https://play.gamepix.com/cut-the-rope/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Cut ropes to feed candy to Om Nom. Physics puzzle classic. Time your cuts.',
    controls: 'Click to cut ropes',
    tags: ['physics', 'puzzle', 'cut-rope'],
  },
  {
    slug: 'bottle-flip-challenge',
    name: 'Bottle Flip Challenge',
    category: 'Arcade',
    emoji: '🍾',
    thumbnail: 'https://img.gamepix.com/games/bottle-flip-challenge/cover/bottle-flip-challenge.png?w=400',
    gameUrl: 'https://play.gamepix.com/bottle-flip-challenge/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Flip the bottle and land it upright. TikTok viral sensation. Can you nail it?',
    controls: 'Click or space to flip',
    tags: ['flip', 'bottle', 'timing'],
  },
  {
    slug: 'fruit-ninja-slice',
    name: 'Fruit Ninja',
    category: 'Action',
    emoji: '🍉',
    thumbnail: 'https://img.gamepix.com/games/fruit-ninja/cover/fruit-ninja.png?w=400',
    gameUrl: 'https://play.gamepix.com/fruit-ninja/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Slice fruit with your blade. Swipe to cut, avoid bombs. Ninja training.',
    controls: 'Swipe to cut',
    tags: ['fruit-ninja', 'slice', 'swipe'],
  },
  {
    slug: 'bricks-breaker',
    name: 'Bricks Breaker',
    category: 'Puzzle',
    emoji: '🧱',
    thumbnail: 'https://img.gamepix.com/games/bricks-breaker/cover/bricks-breaker.png?w=400',
    gameUrl: 'https://play.gamepix.com/bricks-breaker/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Break bricks with a ball. Classic arkanoid. One ball to clear them all?',
    controls: 'Mouse to move paddle',
    tags: ['arkanoid', 'brick-breaker', 'classic'],
  },
  {
    slug: 'candy-crush',
    name: 'Candy Crush',
    category: 'Puzzle',
    emoji: '🍬',
    thumbnail: 'https://img.gamepix.com/games/candy-crush/cover/candy-crush.png?w=400',
    gameUrl: 'https://play.gamepix.com/candy-crush/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Match sweets in this colorful puzzle. Swap and crush candies for high scores.',
    controls: 'Click to swap adjacent candies',
    tags: ['match-3', 'candy', 'puzzle'],
  },
  {
    slug: 'zombie-shooter',
    name: 'Zombie Shooter',
    category: 'Action',
    emoji: '🧟',
    thumbnail: 'https://img.gamepix.com/games/zombie-shooter/cover/zombie-shooter.png?w=400',
    gameUrl: 'https://play.gamepix.com/zombie-shooter/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Survive the zombie apocalypse. Aim and shoot to stay alive.',
    controls: 'Mouse to aim and shoot',
    tags: ['zombie', 'shooter', 'survival'],
  },
  {
    slug: 'temple-run',
    name: 'Temple Run',
    category: 'Racing',
    emoji: '🏃',
    thumbnail: 'https://img.gamepix.com/games/temple-run/cover/temple-run.png?w=400',
    gameUrl: 'https://play.gamepix.com/temple-run/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Run through the ancient temple. Dodge obstacles and collect coins.',
    controls: 'Swipe to turn and jump',
    tags: ['endless-runner', 'action', 'escape'],
  },
  {
    slug: 'angry-birds',
    name: 'Angry Birds',
    category: 'Puzzle',
    emoji: '🐦',
    thumbnail: 'https://img.gamepix.com/games/angry-birds/cover/angry-birds.png?w=400',
    gameUrl: 'https://play.gamepix.com/angry-birds/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Launch birds at structures. Destroy the pigs with physics-based destruction.',
    controls: 'Click and drag to aim, release to launch',
    tags: ['physics', 'slingshot', 'destruction'],
  },
  {
    slug: 'flappy-bird',
    name: 'Flappy Bird',
    category: 'Arcade',
    emoji: '🐤',
    thumbnail: 'https://img.gamepix.com/games/flappy-bird/cover/flappy-bird.png?w=400',
    gameUrl: 'https://play.gamepix.com/flappy-bird/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Flap through pipes. One tap to fly, timing is everything.',
    controls: 'Click or tap to flap',
    tags: ['flappy', 'endless', 'timing'],
  },
  {
    slug: 'subway-surfers',
    name: 'Subway Surfers',
    category: 'Racing',
    emoji: '🏄',
    thumbnail: 'https://img.gamepix.com/games/subway-surfers/cover/subway-surfers.png?w=400',
    gameUrl: 'https://play.gamepix.com/subway-surfers/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Dash through the city subway. Jump, dodge trains, collect coins.',
    controls: 'Swipe to jump and switch lanes',
    tags: ['endless-runner', 'dodge', 'urban'],
  },
  {
    slug: 'chess',
    name: 'Chess',
    category: 'Puzzle',
    emoji: '♟️',
    thumbnail: 'https://img.gamepix.com/games/chess/cover/chess.png?w=400',
    gameUrl: 'https://play.gamepix.com/chess/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Classic chess against AI. Test your strategic thinking.',
    controls: 'Click to select and move pieces',
    tags: ['chess', 'strategy', 'board'],
  },
  {
    slug: 'snake-game',
    name: 'Snake Game',
    category: 'Arcade',
    emoji: '🐍',
    thumbnail: 'https://img.gamepix.com/games/snake-game/cover/snake-game.png?w=400',
    gameUrl: 'https://play.gamepix.com/snake-game/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Eat and grow. Classic snake gameplay with a modern twist.',
    controls: 'Arrow keys to move',
    tags: ['snake', 'classic', 'eat'],
  },
  {
    slug: 'tetris',
    name: 'Tetris',
    category: 'Puzzle',
    emoji: '🟦',
    thumbnail: 'https://img.gamepix.com/games/tetris/cover/tetris.png?w=400',
    gameUrl: 'https://play.gamepix.com/tetris/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Stack blocks and clear lines. The timeless puzzle classic.',
    controls: 'Arrow keys to move and rotate',
    tags: ['tetris', 'blocks', 'classic'],
  },
  {
    slug: 'pac-man',
    name: 'Pac-Man',
    category: 'Arcade',
    emoji: '👻',
    thumbnail: 'https://img.gamepix.com/games/pac-man/cover/pac-man.png?w=400',
    gameUrl: 'https://play.gamepix.com/pac-man/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Navigate the maze, eat dots, avoid ghosts. The arcade legend.',
    controls: 'Arrow keys to move',
    tags: ['pac-man', 'maze', 'classic'],
  },
  {
    slug: 'pinball',
    name: 'Pinball Classic',
    category: 'Arcade',
    emoji: '🎱',
    thumbnail: 'https://img.gamepix.com/games/pinball/cover/pinball.png?w=400',
    gameUrl: 'https://play.gamepix.com/pinball/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Flip and score. Classic pinball action with bouncy physics.',
    controls: 'Space or click to flip',
    tags: ['pinball', 'flipper', 'arcade'],
  },
  {
    slug: 'solitaire',
    name: 'Solitaire',
    category: 'Puzzle',
    emoji: '🃏',
    thumbnail: 'https://img.gamepix.com/games/solitaire/cover/solitaire.png?w=400',
    gameUrl: 'https://play.gamepix.com/solitaire/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Classic Klondike solitaire. Stack cards by suit from King to Ace.',
    controls: 'Click to move cards',
    tags: ['solitaire', 'cards', 'patience'],
  },
  {
    slug: 'soccer',
    name: 'Soccer Master',
    category: 'Sports',
    emoji: '⚽',
    thumbnail: 'https://img.gamepix.com/games/soccer/cover/soccer.png?w=400',
    gameUrl: 'https://play.gamepix.com/soccer/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Kick goals and win matches. Penalty kicks and free shots.',
    controls: 'Click and drag to aim and shoot',
    tags: ['soccer', 'football', 'sports'],
  },
  {
    slug: 'basketball',
    name: 'Basketball Stars',
    category: 'Sports',
    emoji: '🏀',
    thumbnail: 'https://img.gamepix.com/games/basketball/cover/basketball.png?w=400',
    gameUrl: 'https://play.gamepix.com/basketball/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Slam dunks and three-pointers. Basketball action at its finest.',
    controls: 'Click and drag to shoot',
    tags: ['basketball', 'sports', 'dunk'],
  },
  {
    slug: 'tennis-open',
    name: 'Tennis Open',
    category: 'Sports',
    emoji: '🎾',
    thumbnail: 'https://img.gamepix.com/games/tennis-open/cover/tennis-open.png?w=400',
    gameUrl: 'https://play.gamepix.com/tennis-open/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Serve and volley. Challenge opponents in tennis matches.',
    controls: 'Click to swing racket',
    tags: ['tennis', 'sports', 'serve'],
  },
  {
    slug: 'tower-blocks',
    name: 'Tower Blocks',
    category: 'Simulation',
    emoji: '🏗️',
    thumbnail: 'https://img.gamepix.com/games/tower-blocks/cover/tower-blocks.png?w=400',
    gameUrl: 'https://play.gamepix.com/tower-blocks/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Stack blocks to build the tallest tower. Precision placement.',
    controls: 'Click to drop blocks',
    tags: ['stacking', 'precision', 'building'],
  },
  {
    slug: 'farming-simulator',
    name: 'Farming Simulator',
    category: 'Simulation',
    emoji: '🚜',
    thumbnail: 'https://img.gamepix.com/games/farming-simulator/cover/farming-simulator.png?w=400',
    gameUrl: 'https://play.gamepix.com/farming-simulator/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Grow crops and manage your farm. Harvest时节 for profit.',
    controls: 'Click to plant and harvest',
    tags: ['farming', 'simulation', 'crops'],
  },
  {
    slug: 'memory-match',
    name: 'Memory Match',
    category: 'Memory',
    emoji: '🃏',
    thumbnail: 'https://img.gamepix.com/games/memory-match/cover/memory-match.png?w=400',
    gameUrl: 'https://play.gamepix.com/memory-match/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Match pairs of cards. Test and improve your memory.',
    controls: 'Click to flip cards',
    tags: ['memory', 'matching', 'cards'],
  },
  {
    slug: 'stickman-hook',
    name: 'Stickman Hook',
    category: 'Action',
    emoji: '🪝',
    thumbnail: 'https://img.gamepix.com/games/stickman-hook/cover/stickman-hook.png?w=400',
    gameUrl: 'https://play.gamepix.com/stickman-hook/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Swing through levels as a stickman. Time your release perfectly.',
    controls: 'Click to hook and release',
    tags: ['stickman', 'swing', 'physics'],
  },
  {
    slug: 'bubble-shooter',
    name: 'Bubble Shooter',
    category: 'Puzzle',
    emoji: '🫧',
    thumbnail: 'https://img.gamepix.com/games/bubble-shooter/cover/bubble-shooter.png?w=400',
    gameUrl: 'https://play.gamepix.com/bubble-shooter/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Pop bubbles by matching colors. Shoot and match to clear the board.',
    controls: 'Click to shoot bubbles',
    tags: ['bubble', 'shooter', 'match-3'],
  },
  {
    slug: 'bowling',
    name: 'Bowling Master',
    category: 'Sports',
    emoji: '🎳',
    thumbnail: 'https://img.gamepix.com/games/bowling/cover/bowling.png?w=400',
    gameUrl: 'https://play.gamepix.com/bowling/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Strike! Bowl your way to victory. Roll the ball and knock down pins.',
    controls: 'Click and drag to aim and throw',
    tags: ['bowling', 'sports', 'aim'],
  },
  {
    slug: 'mario-kart',
    name: 'Mario Kart Style',
    category: 'Racing',
    emoji: '🏎️',
    thumbnail: 'https://img.gamepix.com/games/mario-kart/cover/mario-kart.png?w=400',
    gameUrl: 'https://play.gamepix.com/mario-kart/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Race through tracks and collect power-ups. Kart racing action!',
    controls: 'Arrow keys to drive',
    tags: ['racing', 'kart', 'Mario'],
  },
  {
    slug: 'monster-truck',
    name: 'Monster Truck',
    category: 'Racing',
    emoji: '🚛',
    thumbnail: 'https://img.gamepix.com/games/monster-truck/cover/monster-truck.png?w=400',
    gameUrl: 'https://play.gamepix.com/monster-truck/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Drive a powerful monster truck over rough terrain.',
    controls: 'Arrow keys to drive',
    tags: ['truck', 'monster', 'offroad'],
  },
  {
    slug: 'doodle-jump',
    name: 'Doodle Jump',
    category: 'Arcade',
    emoji: '✏️',
    thumbnail: 'https://img.gamepix.com/games/doodle-jump/cover/doodle-jump.png?w=400',
    gameUrl: 'https://play.gamepix.com/doodle-jump/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Jump higher and higher by hopping on platforms.',
    controls: 'Click or tap to jump',
    tags: ['doodle', 'jump', 'arcade'],
  },
  {
    slug: 'cut-the-rope',
    name: 'Cut the Rope',
    category: 'Puzzle',
    emoji: '🪢',
    thumbnail: 'https://img.gamepix.com/games/cut-the-rope/cover/cut-the-rope.png?w=400',
    gameUrl: 'https://play.gamepix.com/cut-the-rope/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Cut ropes to feed Om Nom. Physics-based puzzle fun.',
    controls: 'Click and drag to cut ropes',
    tags: ['physics', 'puzzle', 'rope'],
  },
  {
    slug: 'fruit-ninja',
    name: 'Fruit Ninja',
    category: 'Action',
    emoji: '🍎',
    thumbnail: 'https://img.gamepix.com/games/fruit-ninja/cover/fruit-ninja.png?w=400',
    gameUrl: 'https://play.gamepix.com/fruit-ninja/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Slice fruit with your blade. Swipe to cut, avoid bombs.',
    controls: 'Swipe to cut fruit',
    tags: ['fruit', 'ninja', 'slice'],
  },
  {
    slug: 'battle-arena',
    name: 'Battle Arena',
    category: 'Action',
    emoji: '⚔️',
    thumbnail: 'https://img.gamepix.com/games/battle-arena/cover/battle-arena.png?w=400',
    gameUrl: 'https://play.gamepix.com/battle-arena/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Fight other players in an arena. Be the last one standing.',
    controls: 'WASD to move, mouse to attack',
    tags: ['arena', 'battle', 'fighting'],
  },
  {
    slug: 'tower-defense',
    name: 'Tower Defense',
    category: 'Strategy',
    emoji: '🏰',
    thumbnail: 'https://img.gamepix.com/games/tower-defense/cover/tower-defense.png?w=400',
    gameUrl: 'https://play.gamepix.com/tower-defense/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Defend your base with towers. Stop waves of enemies.',
    controls: 'Click to place towers',
    tags: ['tower', 'defense', 'strategy'],
  },
  {
    slug: 'mini-golf',
    name: 'Mini Golf',
    category: 'Sports',
    emoji: '⛳',
    thumbnail: 'https://img.gamepix.com/games/mini-golf/cover/mini-golf.png?w=400',
    gameUrl: 'https://play.gamepix.com/mini-golf/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Putt your way through challenging holes. Master the greens.',
    controls: 'Click and drag to aim and putt',
    tags: ['golf', 'putt', 'sports'],
  },
  {
    slug: 'ice-breaker',
    name: 'Ice Breaker',
    category: 'Puzzle',
    emoji: '🧊',
    thumbnail: 'https://img.gamepix.com/games/ice-breaker/cover/ice-breaker.png?w=400',
    gameUrl: 'https://play.gamepix.com/ice-breaker/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Break through ice and rescue trapped characters.',
    controls: 'Click to break ice',
    tags: ['ice', 'puzzle', 'rescue'],
  },
  {
    slug: 'skating-free',
    name: 'Skating Free',
    category: 'Sports',
    emoji: '🛹',
    thumbnail: 'https://img.gamepix.com/games/skating-free/cover/skating-free.png?w=400',
    gameUrl: 'https://play.gamepix.com/skating-free/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Perform tricks on your skateboard. Master the halfpipe.',
    controls: 'Arrow keys to skate and trick',
    tags: ['skateboard', 'tricks', 'sports'],
  },
  {
    slug: 'gold-miner',
    name: 'Gold Miner',
    category: 'Arcade',
    emoji: '⛏️',
    thumbnail: 'https://img.gamepix.com/games/gold-miner/cover/gold-miner.png?w=400',
    gameUrl: 'https://play.gamepix.com/gold-miner/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Grab gold and gems with your claw machine.',
    controls: 'Click and hold to lower claw',
    tags: ['miner', 'gold', 'claw'],
  },
  {
    slug: 'egg-catcher',
    name: 'Egg Catcher',
    category: 'Arcade',
    emoji: '🥚',
    thumbnail: 'https://img.gamepix.com/games/egg-catcher/cover/egg-catcher.png?w=400',
    gameUrl: 'https://play.gamepix.com/egg-catcher/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Catch falling eggs in your basket. Don\'t let them break!',
    controls: 'Arrow keys to move basket',
    tags: ['egg', 'catch', 'arcade'],
  },
  {
    slug: 'balloon-pop',
    name: 'Balloon Pop',
    category: 'Arcade',
    emoji: '🎈',
    thumbnail: 'https://img.gamepix.com/games/balloon-pop/cover/balloon-pop.png?w=400',
    gameUrl: 'https://play.gamepix.com/balloon-pop/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Pop balloons to score points. Time your pops perfectly.',
    controls: 'Click to pop balloons',
    tags: ['balloon', 'pop', 'timing'],
  },
  {
    slug: 'cannon-basketball',
    name: 'Cannon Basketball',
    category: 'Sports',
    emoji: '🏀',
    thumbnail: 'https://img.gamepix.com/games/cannon-basketball/cover/cannon-basketball.png?w=400',
    gameUrl: 'https://play.gamepix.com/cannon-basketball/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Shoot basketballs into the hoop using a cannon.',
    controls: 'Click and drag to aim and shoot',
    tags: ['basketball', 'cannon', 'physics'],
  },
  {
    slug: 'traffic-control',
    name: 'Traffic Control',
    category: 'Simulation',
    emoji: '🚦',
    thumbnail: 'https://img.gamepix.com/games/traffic-control/cover/traffic-control.png?w=400',
    gameUrl: 'https://play.gamepix.com/traffic-control/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Manage traffic lights and keep cars moving smoothly.',
    controls: 'Click traffic lights to change',
    tags: ['traffic', 'management', 'simulation'],
  },
  {
    slug: 'rope-swing',
    name: 'Rope Swing',
    category: 'Action',
    emoji: '🪢',
    thumbnail: 'https://img.gamepix.com/games/rope-swing/cover/rope-swing.png?w=400',
    gameUrl: 'https://play.gamepix.com/rope-swing/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Swing from rope to rope. Time your release to land safely.',
    controls: 'Click to swing and release',
    tags: ['rope', 'swing', 'timing'],
  },
  {
    slug: 'pet-save',
    name: 'Pet Save',
    category: 'Action',
    emoji: '🐾',
    thumbnail: 'https://img.gamepix.com/games/pet-save/cover/pet-save.png?w=400',
    gameUrl: 'https://play.gamepix.com/pet-save/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Rescue cute pets from danger. Act fast to save them!',
    controls: 'Click to interact',
    tags: ['pets', 'rescue', 'action'],
  },
  {
    slug: 'burger-stack',
    name: 'Burger Stack',
    category: 'Puzzle',
    emoji: '🍔',
    thumbnail: 'https://img.gamepix.com/games/burger-stack/cover/burger-stack.png?w=400',
    gameUrl: 'https://play.gamepix.com/burger-stack/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Stack burger ingredients as high as possible.',
    controls: 'Click to drop ingredients',
    tags: ['burger', 'stack', 'puzzle'],
  },
  {
    slug: 'brick-breaker',
    name: 'Brick Breaker',
    category: 'Arcade',
    emoji: '🧱',
    thumbnail: 'https://img.gamepix.com/games/brick-breaker/cover/brick-breaker.png?w=400',
    gameUrl: 'https://play.gamepix.com/brick-breaker/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Break bricks with a bouncing ball. Classic arcade action.',
    controls: 'Mouse to move paddle',
    tags: ['brick', 'breaker', 'arkanoid'],
  },
  {
    slug: 'laser-puzzle',
    name: 'Laser Puzzle',
    category: 'Puzzle',
    emoji: '💡',
    thumbnail: 'https://img.gamepix.com/games/laser-puzzle/cover/laser-puzzle.png?w=400',
    gameUrl: 'https://play.gamepix.com/laser-puzzle/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Reflect lasers to hit targets. Solve light puzzles.',
    controls: 'Click to place mirrors',
    tags: ['laser', 'puzzle', 'light'],
  },
  {
    slug: 'sushi-party',
    name: 'Sushi Party',
    category: 'Puzzle',
    emoji: '🍣',
    thumbnail: 'https://img.gamepix.com/games/sushi-party/cover/sushi-party.png?w=400',
    gameUrl: 'https://play.gamepix.com/sushi-party/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Match and serve sushi orders. Keep customers happy!',
    controls: 'Click to match sushi',
    tags: ['sushi', 'match', 'puzzle'],
  },
]

export function getGameBySlug(slug: string): Html5Game | undefined {
  return html5Games.find(g => g.slug === slug)
}

export function getFeaturedGame(): Html5Game | undefined {
  return html5Games.find(g => g.featured)
}

export function getGamesByCategory(category: string): Html5Game[] {
  if (category === 'All') return html5Games
  return html5Games.filter(g => g.category === category)
}

export function getRelatedGames(game: Html5Game, limit = 4): Html5Game[] {
  return html5Games
    .filter(g => g.slug !== game.slug && g.category === game.category)
    .slice(0, limit)
}
