export interface Html5Game {
  slug: string
  name: string
  category: string
  emoji: string
  thumbnail: string
  gameUrl: string
  developer?: string
  description: string
  controls?: string
  tags: string[]
  featured?: boolean
}

export const categories = [
  'All',
  'Puzzle',
  'Action',
  'Arcade',
  'Racing',
  'Sports',
  'Simulation',
  'Memory',
  'Stickman',
  'Kids',
]

export const html5Games: Html5Game[] = [
  // === FEATURED (Top Quality) ===
  {
    slug: 'prism-match-3d',
    name: 'Prism Match 3D',
    category: 'Puzzle',
    emoji: '💎',
    thumbnail: 'https://img.gamepix.com/games/prism-match-3d/cover/prism-match-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/prism-match-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Rotate 3D cubes to match colors. Simple concept, addictive gameplay. Can you clear all levels?',
    controls: 'Click and drag to rotate the cube',
    tags: ['match-3', '3d', 'relaxing'],
    featured: true,
  },
  {
    slug: 'merge-royal',
    name: 'Merge Royal',
    category: 'Puzzle',
    emoji: '🃏',
    thumbnail: 'https://img.gamepix.com/games/merge-royal/cover/merge-royal.png?w=400',
    gameUrl: 'https://play.gamepix.com/merge-royal/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Solitaire meets 2048. Merge cards to reach 2048. Two classics, one game.',
    controls: 'Click cards to move and merge',
    tags: ['2048', 'solitaire', 'merge'],
  },
  {
    slug: 'war-the-knights',
    name: 'War the Knights',
    category: 'Action',
    emoji: '⚔️',
    thumbnail: 'https://img.gamepix.com/games/war-the-knights/cover/war-the-knights.png?w=400',
    gameUrl: 'https://play.gamepix.com/war-the-knights/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Deploy knights and win the battle. Strategy meets action. Outsmart your opponent.',
    controls: 'Click to deploy units',
    tags: ['battle', 'strategy', 'knights'],
  },
  {
    slug: 'bus-driver-simulator-3d',
    name: 'Bus Driver Simulator 3D',
    category: 'Simulation',
    emoji: '🚌',
    thumbnail: 'https://img.gamepix.com/games/bus-driver-simulator-3d/cover/bus-driver-simulator-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/bus-driver-simulator-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Be a bus driver. Navigate city streets, pick up passengers, and deliver them safely.',
    controls: 'WASD or arrow keys to drive',
    tags: ['simulation', 'driving', '3d'],
  },
  {
    slug: 'three-cups-game',
    name: 'Three Cups Game',
    category: 'Memory',
    emoji: '🥤',
    thumbnail: 'https://img.gamepix.com/games/three-cups-game/cover/three-cups-game.png?w=400',
    gameUrl: 'https://play.gamepix.com/three-cups-game/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Classic shell game. Track the ball under the cups. How sharp is your eye?',
    controls: 'Click to guess cup location',
    tags: ['memory', 'guess', 'classic'],
  },
  {
    slug: 'body-drop-3d',
    name: 'Body Drop 3D',
    category: 'Simulation',
    emoji: '🎯',
    thumbnail: 'https://img.gamepix.com/games/body-drop-3d/cover/body-drop-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/body-drop-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Launch crash test dummies and watch the ragdoll physics. Maximize damage with limited balls.',
    controls: 'Click to aim and shoot',
    tags: ['simulation', 'physics', 'ragdoll'],
  },
  {
    slug: 'parmesan-partisan',
    name: 'Parmesan Partisan',
    category: 'Arcade',
    emoji: '🧀',
    thumbnail: 'https://img.gamepix.com/games/parmesan-partisan/cover/parmesan-partisan.png?w=400',
    gameUrl: 'https://play.gamepix.com/parmesan-partisan/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Defend your cheese castle from rats. Shotgun action meets tower defense.',
    controls: 'Mouse to aim, click to shoot',
    tags: ['arcade', 'defense', 'shooting'],
  },
  {
    slug: 'kobadoo-emojis',
    name: 'Kobadoo Emojis',
    category: 'Memory',
    emoji: '😀',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-emojis/cover/kobadoo-emojis.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-emojis/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Remember emoji sequences. Gets harder as sequences grow longer. Test your memory.',
    controls: 'Click emojis in order',
    tags: ['memory', 'emoji', 'sequence'],
  },
  {
    slug: 'hoops-and-fruits',
    name: 'Hoops & Fruits',
    category: 'Puzzle',
    emoji: '🏀',
    thumbnail: 'https://img.gamepix.com/games/hoops-and-fruits/cover/hoops-and-fruits.png?w=400',
    gameUrl: 'https://play.gamepix.com/hoops-and-fruits/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Throw balls through hoops to hit fruits. Physics-based puzzle meets Fruit Ninja.',
    controls: 'Click and drag to aim and throw',
    tags: ['drawing', 'physics', 'fruit-ninja'],
  },
  {
    slug: 'turbo-crash-test',
    name: 'Turbo Crash Test',
    category: 'Stickman',
    emoji: '💥',
    thumbnail: 'https://img.gamepix.com/games/turbo-dismounting/cover/turbo-dismounting.png?w=400',
    gameUrl: 'https://play.gamepix.com/turbo-dismounting/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Create epic crashes with ragdoll physics. Unlock vehicles and watch the chaos.',
    controls: 'Click obstacles to trigger crashes',
    tags: ['stickman', 'physics', 'crash'],
  },
  {
    slug: 'cerkio',
    name: 'Cerkio',
    category: 'Arcade',
    emoji: '🎯',
    thumbnail: 'https://img.gamepix.com/games/cerkio/cover/cerkio.png?w=400',
    gameUrl: 'https://play.gamepix.com/cerkio/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Launch a ball into the target. 30 levels of precision timing. One-touch gameplay.',
    controls: 'Click to throw ball',
    tags: ['ball', 'accuracy', 'one-touch'],
  },
  {
    slug: 'gelatino',
    name: 'Gelatino',
    category: 'Arcade',
    emoji: '🍦',
    thumbnail: 'https://img.gamepix.com/games/gelatino/cover/gelatino.png?w=400',
    gameUrl: 'https://play.gamepix.com/gelatino/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Swing a popsicle past traps. Collect ice cubes, dodge heat. Will you melt or prevail?',
    controls: 'Click to swing',
    tags: ['arcade', 'timing', 'swing'],
  },
  {
    slug: 'penalty-kick-wiz',
    name: 'Penalty Kick Wiz',
    category: 'Sports',
    emoji: '⚽',
    thumbnail: 'https://img.gamepix.com/games/penalty-kick-wiz/cover/penalty-kick-wiz.png?w=400',
    gameUrl: 'https://play.gamepix.com/penalty-kick-wiz/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Penalty shootout. Goalkeeper vs striker. Every goal is satisfying.',
    controls: 'Swipe to shoot',
    tags: ['sports', 'soccer', 'penalty'],
  },
  {
    slug: 'stickman-warriors',
    name: 'Stickman Warriors',
    category: 'Stickman',
    emoji: '🦸',
    thumbnail: 'https://img.gamepix.com/games/stickman-warriors/cover/stickman-warriors.png?w=400',
    gameUrl: 'https://play.gamepix.com/stickman-warriors/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Stickman combat with special moves. Combos, ultimates, and flashy effects.',
    controls: 'Click to attack, swipe for combos',
    tags: ['stickman', 'fighting', 'action'],
  },
  {
    slug: 'kobadoo-numbers',
    name: 'Kobadoo Numbers',
    category: 'Memory',
    emoji: '🔢',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-numbers/cover/kobadoo-numbers.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-numbers/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Remember number sequences. Longer sequences as you progress. Brain teaser.',
    controls: 'Click numbers in order',
    tags: ['memory', 'numbers', 'sequence'],
  },
  {
    slug: 'flamit',
    name: 'Flamit',
    category: 'Action',
    emoji: '🔥',
    thumbnail: 'https://img.gamepix.com/games/flamit/cover/flamit.png?w=400',
    gameUrl: 'https://play.gamepix.com/flamit/embed?sid=7O017',
    developer: 'GamePix',
    description: 'A flaming stickman running adventure. Jump, dash, survive. Never extinguish.',
    controls: 'Tap or click to jump',
    tags: ['adventure', 'runner', 'fire'],
  },
  {
    slug: 'stickman-street-fighting-3d',
    name: 'Stickman Street Fighting 3D',
    category: 'Stickman',
    emoji: '👊',
    thumbnail: 'https://img.gamepix.com/games/stickman-street-fighting-3d/cover/stickman-street-fighting-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/stickman-street-fighting-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: '3D street fighting. Punches, kicks, combos. Become the toughest stickman.',
    controls: 'Tap to punch/kick, swipe to dodge',
    tags: ['stickman', 'fighting', '3d'],
  },
  {
    slug: 'morphit',
    name: 'Morphit',
    category: 'Puzzle',
    emoji: '🟦',
    thumbnail: 'https://img.gamepix.com/games/morphit/cover/morphit.png?w=400',
    gameUrl: 'https://play.gamepix.com/morphit/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Morph shapes to pass obstacles. Adapt and transform. Flexible puzzle solving.',
    controls: 'Drag to morph shape',
    tags: ['puzzle', 'shapes', 'morph'],
  },
  {
    slug: 'robot-band-find-differences',
    name: 'Robot Band',
    category: 'Puzzle',
    emoji: '🤖',
    thumbnail: 'https://img.gamepix.com/games/robot-band/cover/robot-band.png?w=400',
    gameUrl: 'https://play.gamepix.com/robot-band/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Find the differences between two images. Robot band theme. Train your eye.',
    controls: 'Click on differences',
    tags: ['puzzle', 'difference', 'robots'],
  },
  {
    slug: 'my-first-100-words',
    name: 'My First 100 Words',
    category: 'Kids',
    emoji: '📚',
    thumbnail: 'https://img.gamepix.com/games/my-first-100-words/cover/my-first-100-words.png?w=400',
    gameUrl: 'https://play.gamepix.com/my-first-100-words/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Learn 100 words with pictures. Match words to images. Educational fun.',
    controls: 'Click on matching words',
    tags: ['educational', 'words', 'kids'],
  },
  {
    slug: 'sokoballs',
    name: 'Sokoballs',
    category: 'Puzzle',
    emoji: '🧩',
    thumbnail: 'https://img.gamepix.com/games/sokoballs/cover/sokoballs.png?w=400',
    gameUrl: 'https://play.gamepix.com/sokoballs/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Physics puzzle. Shoot balls into holes. Think before you shoot.',
    controls: 'Click to shoot ball',
    tags: ['puzzle', 'physics', 'ball'],
  },
  {
    slug: 'going-right',
    name: 'Going Right',
    category: 'Action',
    emoji: '➡️',
    thumbnail: 'https://img.gamepix.com/games/going-right/cover/going-right.png?w=400',
    gameUrl: 'https://play.gamepix.com/going-right/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Can only go right. Collect coins, avoid obstacles. Simple but challenging.',
    controls: 'Tap to jump',
    tags: ['endless', 'runner', 'simple'],
  },
  {
    slug: 'funny-shooter-2',
    name: 'Funny Shooter 2',
    category: 'Action',
    emoji: '🔫',
    thumbnail: 'https://img.gamepix.com/games/funny-shooter-2/cover/funny-shooter-2.png?w=400',
    gameUrl: 'https://play.gamepix.com/funny-shooter-2/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Shoot weird monsters with silly weapons. Zany enemies, laugh-out-loud action.',
    controls: 'Mouse to aim, click to shoot',
    tags: ['shooter', 'zombie', 'funny'],
  },
  {
    slug: 'canjump',
    name: 'Canjump',
    category: 'Action',
    emoji: '🦘',
    thumbnail: 'https://img.gamepix.com/games/canjump/cover/canjump.png?w=400',
    gameUrl: 'https://play.gamepix.com/canjump/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Jump on blocks to climb higher. How high can you go? Vertical platformer.',
    controls: 'Click to jump',
    tags: ['platformer', 'jumping', 'vertical'],
  },
  {
    slug: 'moto-x3m-spooky',
    name: 'Moto X3M Spooky',
    category: 'Racing',
    emoji: '🏍️',
    thumbnail: 'https://img.gamepix.com/games/moto-x3m-spooky-land/cover/moto-x3m-spooky-land.png?w=400',
    gameUrl: 'https://play.gamepix.com/moto-x3m-spooky-land/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Motorcycle stunts with flips and obstacles. Spooky halloween edition. Physics-based.',
    controls: 'Arrow keys to balance and accelerate',
    tags: ['racing', 'motorcycle', 'physics'],
  },
  {
    slug: 'slope-racing-3d',
    name: 'Slope Racing 3D',
    category: 'Racing',
    emoji: '🎿',
    thumbnail: 'https://img.gamepix.com/games/slope-racing-3d/cover/slope-racing-3d.png?w=400',
    gameUrl: 'https://play.gamepix.com/slope-racing-3d/embed?sid=7O017',
    developer: 'GamePix',
    description: "Slope racing down snowy hills. Control speed, don't fly off. Adrenaline rush.",
    controls: 'Arrow keys to control',
    tags: ['racing', '3d', 'slope'],
  },
  {
    slug: 'tentrix',
    name: 'TenTrix',
    category: 'Puzzle',
    emoji: '🧱',
    thumbnail: 'https://img.gamepix.com/games/tentrix/cover/tentrix.png?w=400',
    gameUrl: 'https://play.gamepix.com/tentrix/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Tetris evolved. Fill rows to clear blocks. Classic with a modern twist.',
    controls: 'Arrow keys to move and rotate',
    tags: ['tetris', 'block', 'puzzle'],
  },
  {
    slug: 'kobadoo-shapes',
    name: 'Kobadoo Shapes',
    category: 'Memory',
    emoji: '🔷',
    thumbnail: 'https://img.gamepix.com/games/kobadoo-shapes/cover/kobadoo-shapes.png?w=400',
    gameUrl: 'https://play.gamepix.com/kobadoo-shapes/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Remember shape sequences. Complex patterns as you level up. Short-term memory training.',
    controls: 'Click shapes in order',
    tags: ['memory', 'shapes', 'sequence'],
  },
  {
    slug: 'royal-couple-halloween',
    name: 'Royal Couple Halloween',
    category: 'Kids',
    emoji: '👻',
    thumbnail: 'https://img.gamepix.com/games/royal-couple-halloween-party/cover/royal-couple-halloween-party.png?w=400',
    gameUrl: 'https://play.gamepix.com/royal-couple-halloween-party/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Dress up the royal couple for Halloween. Costumes, makeup, party time!',
    controls: 'Click to dress up',
    tags: ['dress-up', 'halloween', 'kids'],
  },
  {
    slug: 'pool-8-ball',
    name: '8 Ball Pool',
    category: 'Sports',
    emoji: '🎱',
    thumbnail: 'https://img.gamepix.com/games/pool-8-ball/cover/pool-8-ball.png?w=400',
    gameUrl: 'https://play.gamepix.com/pool-8-ball/embed?sid=7O017',
    developer: 'GamePix',
    description: '8 ball pool classic. Aim, shoot, pocket. Become a pool master.',
    controls: 'Click and drag to aim and shoot',
    tags: ['pool', 'sports', 'billiards'],
  },
  {
    slug: 'candy-bubble',
    name: 'Candy Bubble',
    category: 'Puzzle',
    emoji: '🍬',
    thumbnail: 'https://img.gamepix.com/games/candy-bubble/cover/candy-bubble.png?w=400',
    gameUrl: 'https://play.gamepix.com/candy-bubble/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Bubble shooter with candy theme. Match colors, clear bubbles. Sweet puzzler.',
    controls: 'Mouse to aim, click to shoot',
    tags: ['bubble-shooter', 'match-3', 'candy'],
  },
  {
    slug: 'cut-the-rope',
    name: 'Cut the Rope',
    category: 'Puzzle',
    emoji: '🍬',
    thumbnail: 'https://img.gamepix.com/games/cut-the-rope/cover/cut-the-rope.png?w=400',
    gameUrl: 'https://play.gamepix.com/cut-the-rope/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Cut ropes to feed candy to Om Nom. Physics puzzle classic. Time your cuts.',
    controls: 'Click to cut ropes',
    tags: ['physics', 'puzzle', 'cut-rope'],
  },
  {
    slug: 'bottle-flip-challenge',
    name: 'Bottle Flip Challenge',
    category: 'Arcade',
    emoji: '🍾',
    thumbnail: 'https://img.gamepix.com/games/bottle-flip-challenge/cover/bottle-flip-challenge.png?w=400',
    gameUrl: 'https://play.gamepix.com/bottle-flip-challenge/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Flip the bottle and land it upright. TikTok viral sensation. Can you nail it?',
    controls: 'Click or space to flip',
    tags: ['flip', 'bottle', 'timing'],
  },
  {
    slug: 'fruit-ninja-slice',
    name: 'Fruit Ninja',
    category: 'Action',
    emoji: '🍉',
    thumbnail: 'https://img.gamepix.com/games/fruit-ninja/cover/fruit-ninja.png?w=400',
    gameUrl: 'https://play.gamepix.com/fruit-ninja/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Slice fruit with your blade. Swipe to cut, avoid bombs. Ninja training.',
    controls: 'Swipe to cut',
    tags: ['fruit-ninja', 'slice', 'swipe'],
  },
  {
    slug: 'bricks-breaker',
    name: 'Bricks Breaker',
    category: 'Puzzle',
    emoji: '🧱',
    thumbnail: 'https://img.gamepix.com/games/bricks-breaker/cover/bricks-breaker.png?w=400',
    gameUrl: 'https://play.gamepix.com/bricks-breaker/embed?sid=7O017',
    developer: 'GamePix',
    description: 'Break bricks with a ball. Classic arkanoid. One ball to clear them all?',
    controls: 'Mouse to move paddle',
    tags: ['arkanoid', 'brick-breaker', 'classic'],
  },
]

export function getGameBySlug(slug: string): Html5Game | undefined {
  return html5Games.find(g => g.slug === slug)
}

export function getFeaturedGame(): Html5Game | undefined {
  return html5Games.find(g => g.featured)
}

export function getGamesByCategory(category: string): Html5Game[] {
  if (category === 'All') return html5Games
  return html5Games.filter(g => g.category === category)
}

export function getRelatedGames(game: Html5Game, limit = 4): Html5Game[] {
  return html5Games
    .filter(g => g.slug !== game.slug && g.category === game.category)
    .slice(0, limit)
}
